export interface CompositionOptions {readonly caseId:string;readonly width:number;readonly height:number;readonly duration:number}

const clip=(id:string,start:number,duration:number,track:number,body:string)=>`<section id="${id}" class="clip" data-start="${start}" data-duration="${duration}" data-track-index="${track}"><div class="fill">${body}</div></section>`;

const typography=()=>`<div class="type-wrap"><h1 id="hf-title">Determinism<br>is a feature.</h1><div id="hf-accent" class="accent"></div><p id="hf-copy">Exact time in. Verified frames out. The baseline measures layout, masking, local font loading, opacity, and transform behavior.</p></div>`;
const vector=()=>`<svg id="hf-vector" viewBox="0 0 900 600"><defs><linearGradient id="hf-g"><stop stop-color="#65d6ff"/><stop offset="1" stop-color="#8b5cf6"/></linearGradient><clipPath id="hf-c"><circle id="hf-mask" cx="450" cy="300" r="220"/></clipPath><filter id="hf-b"><feGaussianBlur stdDeviation="12"/></filter></defs><circle cx="470" cy="330" r="220" fill="#000" opacity=".7" filter="url(#hf-b)"/><path id="hf-shape" d="M120 430 C260 80 620 80 780 430 L660 520 H240Z" fill="url(#hf-g)" clip-path="url(#hf-c)"/><path id="hf-path" d="M160 440 C300 160 600 130 735 405" fill="none" stroke="#fff" stroke-width="12" stroke-dasharray="900" stroke-dashoffset="900"/></svg>`;
const chart=()=>`<div class="chart-wrap"><h2>Measured pipeline stages</h2><div class="bars" data-layout-allow-overflow>${[42,76,61,88].map((v,i)=>`<div class="bar-shell"><span class="value" data-layout-allow-overflow>${v}</span><div id="hf-bar-${i}" class="bar" style="height:${v}%"></div><span class="bar-label" data-layout-allow-overflow>${["Parse","Seek","Capture","Encode"][i]}</span></div>`).join("")}</div></div>`;
const three=(id="hf-three")=>`<canvas id="${id}" class="three-canvas"></canvas><div class="three-label">Exact-time 3D</div>`;

const content=(caseId:string,duration:number)=>{
  if(caseId==="typography-layout") return clip("hf-typography",0,duration,1,typography());
  if(caseId==="vector-effects") return clip("hf-vectors",0,duration,1,vector());
  if(caseId==="chart-diagram") return clip("hf-chart",0,duration,1,chart());
  if(caseId==="media-frame-sampling") return `<video id="hf-source-video" class="clip" src="assets/color-coded-source.mp4" data-start="0" data-duration="${duration}" data-track-index="1" data-media-start="0.5" muted playsinline></video><div id="hf-media-frame" class="media-frame"></div>`;
  if(caseId==="audio-captions"){const s=duration/8;return `${clip("hf-audio-visual",0,duration,1,`<div class="caption-stack"><div id="hf-caption-a">Deterministic beginnings</div><div id="hf-caption-b">Measured motion</div><div id="hf-caption-c">Verified output</div></div>`)}<audio id="hf-audio-a" src="assets/clip-a.wav" data-start="0" data-duration="${2*s}" data-track-index="10" data-volume="0.8"></audio><audio id="hf-audio-b" src="assets/clip-b.wav" data-start="${3*s}" data-duration="${2*s}" data-track-index="10" data-volume="0.8"></audio><audio id="hf-audio-c" src="assets/clip-c.wav" data-start="${6*s}" data-duration="${2*s}" data-track-index="10" data-volume="0.8"></audio>`;}
  if(caseId==="3d-scene") return clip("hf-3d",0,duration,1,three());
  if(caseId!=="mixed-2d-3d") throw new Error(`Unknown case: ${caseId}`);
  const s1=duration*.2;const s2=duration*7/15;const s3=duration*.8;
  const s=duration/15;return `${clip("hf-mixed-title",0,s1,1,typography())}${clip("hf-mixed-chart",s1,s2-s1,2,chart())}${clip("hf-mixed-three",s2,s3-s2,3,three("hf-three-mixed"))}${clip("hf-mixed-cta",s3,duration-s3,4,`<div class="cta"><strong>Render. Verify. Trust.</strong><span>CineKernel Phase 0.1</span></div>`)}<audio id="hf-mixed-audio-a" src="assets/clip-a.wav" data-start="0" data-duration="${2*s}" data-track-index="10" data-volume="0.45"></audio><audio id="hf-mixed-audio-b" src="assets/clip-b.wav" data-start="${6*s}" data-duration="${2*s}" data-track-index="10" data-volume="0.45"></audio><audio id="hf-mixed-audio-c" src="assets/clip-c.wav" data-start="${12*s}" data-duration="${2*s}" data-track-index="10" data-volume="0.45"></audio>`;
};

export const createComposition=({caseId,width,height,duration}:CompositionOptions):string=>`<!doctype html>
<html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=${width},height=${height}"/><title>CineKernel HyperFrames Baseline</title><script src="vendor/gsap.min.js"></script><style>
@font-face{font-family:CKInter;src:url('assets/font/inter-latin.woff2') format('woff2');font-weight:400;font-display:block}*{box-sizing:border-box}html,body{margin:0;width:${width}px;height:${height}px;overflow:hidden;background:#050c1c;font-family:CKInter,sans-serif;color:#e8f7ff}#root{position:relative;width:${width}px;height:${height}px;overflow:hidden}.clip{position:absolute;inset:0}.fill{position:absolute;inset:0;background:linear-gradient(135deg,#050c1c,#231344);overflow:hidden}.type-wrap{height:100%;display:flex;flex-direction:column;justify-content:center;padding:10%}.type-wrap h1{font-size:${Math.round(width*0.058)}px;line-height:1.02;letter-spacing:-5px;margin:0;max-width:70%;}.type-wrap p{font-size:${Math.round(width*0.016)}px;line-height:1.45;color:#91a7bd;max-width:55%;margin-top:32px}.accent{display:block;width:62%;height:10px;background:linear-gradient(90deg,#65d6ff,#8b5cf6);margin-top:36px;transform-origin:left}#hf-vector{width:75%;height:75%;position:absolute;left:12.5%;top:12.5%;filter:drop-shadow(0 35px 45px rgba(0,0,0,.5));mix-blend-mode:screen}.chart-wrap{height:100%;padding:10%;display:flex;flex-direction:column;justify-content:center}.chart-wrap h2{font-size:${Math.round(width*0.038)}px;margin:0 0 50px}.bars{display:flex;height:56%;align-items:end;gap:6%;border-bottom:2px solid #36506b}.bar-shell{flex:1;height:100%;position:relative;display:flex;align-items:end}.bar{display:block;width:100%;background:linear-gradient(180deg,#65d6ff,#8b5cf6);border-radius:18px 18px 0 0;transform-origin:bottom;box-shadow:0 20px 50px rgba(101,214,255,.18)}.value{position:absolute;top:-42px;width:100%;text-align:center;font-size:${Math.round(width*0.016)}px}.bar-label{position:absolute;bottom:-36px;width:100%;text-align:center;color:#91a7bd;font-size:${Math.round(width*0.012)}px}#hf-source-video{width:76%;height:70%;left:12%;top:15%;object-fit:cover;border-radius:30px;transform:scale(1.12)}.media-frame{position:absolute;left:10%;top:12%;width:80%;height:76%;border:3px solid #65d6ff;border-radius:36px;pointer-events:none}.caption-stack{height:100%;display:grid;place-items:center;font-size:${Math.round(width*0.044)}px}.caption-stack>div{position:absolute;opacity:0}.three-canvas{width:100%;height:100%;display:block}.three-label{position:absolute;left:5%;top:7%;font-size:${Math.round(width*0.015)}px;letter-spacing:3px;text-transform:uppercase;padding:16px 24px;background:rgba(5,12,28,.72);border:1px solid #65d6ff}.cta{height:100%;display:grid;place-content:center;text-align:center}.cta strong{font-size:${Math.round(width*0.048)}px}.cta span{font-size:${Math.round(width*0.015)}px;color:#65d6ff;margin-top:28px}
</style></head><body><main id="root" data-composition-id="main" data-start="0" data-width="${width}" data-height="${height}" data-duration="${duration}" data-fps="30">${content(caseId,duration)}</main>
<script>window.__timelines=window.__timelines||{};const tl=gsap.timeline({paused:true});
if(document.querySelector('#hf-title')){tl.fromTo('#hf-title',{y:70,opacity:0},{y:0,opacity:1,duration:1.2,ease:'power3.out'},0);tl.fromTo('#hf-accent',{scaleX:0},{scaleX:1,duration:0.9,ease:'power2.out'},.45);tl.fromTo('#hf-copy',{y:30,opacity:0},{y:0,opacity:1,duration:1,ease:'power2.out'},.7)}
if(document.querySelector('#hf-shape')){tl.fromTo('#hf-shape',{opacity:0,scale:.5},{opacity:1,scale:1,duration:2,ease:'power3.out'},0);tl.to('#hf-path',{strokeDashoffset:0,duration:3,ease:'none'},0)}
document.querySelectorAll('.bar').forEach((bar,index)=>tl.fromTo(bar,{scaleY:0},{scaleY:1,duration:1.2,ease:'power3.out'},index*.3));
document.querySelectorAll('.three-label').forEach(label=>tl.fromTo(label,{x:24,opacity:.65},{x:0,opacity:1,duration:1.5,ease:'power2.out'},0));
if(document.querySelector('#hf-caption-a')){tl.fromTo('#hf-caption-a',{opacity:0},{opacity:1,duration:.2},0).to('#hf-caption-a',{opacity:0,duration:.2},1.8);tl.fromTo('#hf-caption-b',{opacity:0},{opacity:1,duration:.2},3).to('#hf-caption-b',{opacity:0,duration:.2},4.8);tl.fromTo('#hf-caption-c',{opacity:0},{opacity:1,duration:.2},6)}
window.__timelines['main']=tl;</script>
<script type="module">import * as THREE from './vendor/three.module.js';for(const canvas of document.querySelectorAll('.three-canvas')){const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true});renderer.setSize(${width},${height},false);renderer.setPixelRatio(1);const scene=new THREE.Scene();scene.background=new THREE.Color(0x050c1c);const camera=new THREE.PerspectiveCamera(40,${width}/${height},.1,100);const textureCanvas=document.createElement('canvas');textureCanvas.width=64;textureCanvas.height=64;const context=textureCanvas.getContext('2d');for(let y=0;y<8;y++)for(let x=0;x<8;x++){context.fillStyle=(x+y)%2===0?'#2ed5ff':'#8b5cf6';context.fillRect(x*8,y*8,8,8)}const texture=new THREE.CanvasTexture(textureCanvas);texture.colorSpace=THREE.SRGBColorSpace;const cube=new THREE.Mesh(new THREE.BoxGeometry(2.3,2.3,2.3),new THREE.MeshStandardMaterial({map:texture,color:0x65d6ff,roughness:.28,metalness:.35}));scene.add(cube);scene.add(new THREE.HemisphereLight(0xffffff,0x16213d,1.1));const key=new THREE.DirectionalLight(0xffffff,2);key.position.set(5,7,4);scene.add(key);const floor=new THREE.Mesh(new THREE.PlaneGeometry(12,12),new THREE.MeshStandardMaterial({color:0x111b33,roughness:.9}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.8;scene.add(floor);function renderAt(time){cube.rotation.y=time*.7;cube.rotation.x=time*.18;camera.position.set(Math.sin(time*.22)*4.5,2.5,Math.cos(time*.22)*4.5);camera.lookAt(0,0,0);renderer.render(scene,camera)}window.addEventListener('hf-seek',event=>renderAt(event.detail.time));renderAt(window.__hfThreeTime||0)}</script></body></html>`;
