import {ThreeCanvas} from "@remotion/three";
import {loadFont} from "@remotion/fonts";
import {Audio, Video} from "@remotion/media";
import {useLoader} from "@react-three/fiber";
import React from "react";
import {AbsoluteFill, Easing, Sequence, interpolate, staticFile, useCurrentFrame, useVideoConfig} from "remotion";
import {TextureLoader} from "three";
import {z} from "zod";

loadFont({family: "CineKernelInter", url: staticFile("font/inter-latin.woff2"), format: "woff2", weight: "400"});

export const benchmarkSchema = z.object({caseId: z.string(), width: z.number().int().positive(), height: z.number().int().positive(), durationSeconds: z.number().positive()});
export type BenchmarkProps = z.infer<typeof benchmarkSchema>;

const palette = {ink: "#e8f7ff", muted: "#91a7bd", cyan: "#65d6ff", violet: "#8b5cf6", bg: "#050c1c"};
const base: React.CSSProperties = {fontFamily: "CineKernelInter, sans-serif", background: `linear-gradient(135deg, ${palette.bg}, #231344)`, color: palette.ink};
const ease = Easing.bezier(0.16, 1, 0.3, 1);

export const Benchmark: React.FC<BenchmarkProps> = ({caseId}) => {
  const content = caseId === "typography-layout" ? <Typography /> : caseId === "vector-effects" ? <Vector /> : caseId === "chart-diagram" ? <Chart /> : caseId === "media-frame-sampling" ? <MediaSampling /> : caseId === "audio-captions" ? <AudioCaptions /> : caseId === "3d-scene" ? <Scene3D overlay /> : <Mixed />;
  return <AbsoluteFill style={base}>{content}</AbsoluteFill>;
};

const Typography = () => {const frame=useCurrentFrame();const {fps}=useVideoConfig();const p=interpolate(frame,[0,fps*1.2],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease});return <AbsoluteFill style={{justifyContent:"center",padding:"10%",overflow:"hidden"}}><div style={{fontSize:112,lineHeight:1.02,letterSpacing:-5,opacity:p,translate:`0px ${(1-p)*70}px`,maxWidth:1200}}>Determinism<br/>is a feature.</div><div style={{height:10,width:"62%",background:`linear-gradient(90deg,${palette.cyan},${palette.violet})`,scale:`${p} 1`,transformOrigin:"left",marginTop:36}}/><p style={{fontSize:30,lineHeight:1.45,color:palette.muted,maxWidth:850,opacity:interpolate(frame,[fps*0.7,fps*1.8],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"})}}>Exact time in. Verified frames out. The baseline measures layout, masking, local font loading, opacity, and transform behavior.</p></AbsoluteFill>};

const Vector = () => {const frame=useCurrentFrame();const {fps}=useVideoConfig();const p=interpolate(frame,[0,fps*3],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease});return <AbsoluteFill style={{alignItems:"center",justifyContent:"center"}}><svg viewBox="0 0 900 600" style={{width:"75%",height:"75%",filter:"drop-shadow(0 35px 45px rgba(0,0,0,.5))",mixBlendMode:"screen"}}><defs><linearGradient id="remotion-g" x1="0" x2="1"><stop stopColor={palette.cyan}/><stop offset="1" stopColor={palette.violet}/></linearGradient><clipPath id="remotion-c"><circle cx="450" cy="300" r={220*p}/></clipPath><filter id="remotion-b"><feGaussianBlur stdDeviation="12"/></filter></defs><circle cx="470" cy="330" r="220" fill="#000" opacity=".7" filter="url(#remotion-b)"/><path d="M120 430 C260 80 620 80 780 430 L660 520 H240Z" fill="url(#remotion-g)" clipPath="url(#remotion-c)" opacity={p}/><path d="M160 440 C300 160 600 130 735 405" fill="none" stroke="#fff" strokeWidth="12" strokeDasharray="900" strokeDashoffset={900*(1-p)}/></svg></AbsoluteFill>};

const Chart = ({compact=false}:{readonly compact?:boolean}) => {const frame=useCurrentFrame();const {fps}=useVideoConfig();const values=[42,76,61,88];const labels=["Parse","Seek","Capture","Encode"];return <AbsoluteFill style={{padding:compact?"14% 12%":"10%",justifyContent:"center"}}><div style={{fontSize:compact?52:72,marginBottom:50}}>Measured pipeline stages</div><div style={{display:"flex",height:"56%",alignItems:"end",gap:"6%",borderBottom:"2px solid #36506b"}}>{values.map((value,index)=>{const p=interpolate(frame,[index*0.3*fps,(index*0.3+1.2)*fps],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp",easing:ease});return <div key={value} style={{flex:1,height:`${value}%`,scale:`1 ${p}`,transformOrigin:"bottom",background:`linear-gradient(180deg,${palette.cyan},${palette.violet})`,borderRadius:"18px 18px 0 0",position:"relative",boxShadow:"0 20px 50px rgba(101,214,255,.18)"}}><span style={{position:"absolute",top:-52,width:"100%",textAlign:"center",fontSize:30}}>{Math.round(value*p)}</span><span style={{position:"absolute",bottom:-46,width:"100%",textAlign:"center",fontSize:22,color:palette.muted}}>{labels[index]}</span></div>})}</div></AbsoluteFill>};

const MediaSampling = () => {const {width,height}=useVideoConfig();return <AbsoluteFill style={{alignItems:"center",justifyContent:"center"}}><div style={{width:width*0.76,height:height*0.7,overflow:"hidden",borderRadius:30,boxShadow:"0 35px 80px #000"}}><Video src={staticFile("color-coded-source.mp4")} trimBefore={15} muted style={{width:"100%",height:"100%",objectFit:"cover",scale:"1.12"}}/></div></AbsoluteFill>};

const AudioCaptions = () => {const frame=useCurrentFrame();const {fps,durationInFrames}=useVideoConfig();const scale=durationInFrames/(8*fps);const at=(seconds:number)=>Math.round(seconds*fps*scale);const caption=frame<at(2)?"Deterministic beginnings":frame>=at(3)&&frame<at(5)?"Measured motion":frame>=at(6)?"Verified output":"Silence is evidence too";return <AbsoluteFill style={{alignItems:"center",justifyContent:"center"}}><Sequence from={at(0)} durationInFrames={at(2)} layout="none"><Audio src={staticFile("clip-a.wav")} volume={0.8}/></Sequence><Sequence from={at(3)} durationInFrames={at(2)} layout="none"><Audio src={staticFile("clip-b.wav")} volume={0.8}/></Sequence><Sequence from={at(6)} durationInFrames={at(2)} layout="none"><Audio src={staticFile("clip-c.wav")} volume={0.8}/></Sequence><div style={{fontSize:84,opacity:interpolate(frame%Math.max(1,Math.round(fps*scale)),[0,Math.max(1,Math.round(10*scale))],[0,1],{extrapolateRight:"clamp"})}}>{caption}</div><div style={{position:"absolute",bottom:100,fontSize:24,color:palette.muted}}>Three registered clips · 440 Hz · 660 Hz · 880 Hz</div></AbsoluteFill>};

const Scene3D = ({overlay=false}:{readonly overlay?:boolean}) => {const frame=useCurrentFrame();const {width,height,fps}=useVideoConfig();const t=frame/fps;const texture=useLoader(TextureLoader,staticFile("texture.png"));return <AbsoluteFill><ThreeCanvas width={width} height={height} camera={{position:[Math.sin(t*0.22)*4.5,2.5,Math.cos(t*0.22)*4.5],fov:40}}><ambientLight intensity={0.45}/><directionalLight position={[5,7,4]} intensity={1.7}/><mesh rotation={[t*0.18,t*0.7,0]} castShadow><boxGeometry args={[2.3,2.3,2.3]}/><meshStandardMaterial map={texture} color={palette.cyan} roughness={0.28} metalness={0.35}/></mesh><mesh position={[0,-1.8,0]} rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry args={[12,12]}/><meshStandardMaterial color="#111b33" roughness={0.9}/></mesh></ThreeCanvas>{overlay&&<div style={{position:"absolute",left:80,top:70,fontSize:28,letterSpacing:3,textTransform:"uppercase",padding:"16px 24px",background:"rgba(5,12,28,.72)",border:`1px solid ${palette.cyan}`}}>Exact-time 3D</div>}</AbsoluteFill>};

const Mixed = () => {const {durationInFrames}=useVideoConfig();const a=Math.round(durationInFrames*.2);const b=Math.round(durationInFrames*4/15);const c=Math.round(durationInFrames/3);const d=durationInFrames-a-b-c;const scale=durationInFrames/450;const at=(frames:number)=>Math.round(frames*scale);return <AbsoluteFill><Sequence from={at(0)} durationInFrames={at(60)} layout="none"><Audio src={staticFile("clip-a.wav")} volume={0.45}/></Sequence><Sequence from={at(180)} durationInFrames={at(60)} layout="none"><Audio src={staticFile("clip-b.wav")} volume={0.45}/></Sequence><Sequence from={at(360)} durationInFrames={durationInFrames-at(360)} layout="none"><Audio src={staticFile("clip-c.wav")} loop volume={(frame)=>frame<at(60)?0.45:0}/></Sequence><Sequence from={0} durationInFrames={a}><Typography/></Sequence><Sequence from={a} durationInFrames={b}><Chart compact/></Sequence><Sequence from={a+b} durationInFrames={c}><Scene3D overlay/></Sequence><Sequence from={a+b+c} durationInFrames={d}><AbsoluteFill style={{alignItems:"center",justifyContent:"center",background:"radial-gradient(circle at center,#18365e,#050c1c)"}}><div style={{fontSize:92}}>Render. Verify. Trust.</div><div style={{fontSize:26,color:palette.cyan,marginTop:28}}>CineKernel Phase 0.1</div></AbsoluteFill></Sequence></AbsoluteFill>};
