use crate::{lock::UpstreamLock, source_index};
use anyhow::{Context, Result};
use serde_json::{json, Value};
use std::path::Path;

pub fn model(root: &Path, mut value: Value, lock: &UpstreamLock) -> Result<Value> {
    value["model_version"] = json!("r0.02.4");
    value["generated_at"] = json!("2026-08-16T00:00:00Z");
    source_index::remediate(root, &mut value, lock)?;
    normalize_claims(&mut value)?;
    value["authoring_surfaces"] = authoring_surfaces();
    let (nodes, edges) = architecture_graph();
    value["architecture_nodes"] = nodes;
    value["architecture_edges"] = edges.clone();
    value["boundary_contracts"] = boundary_contracts(&edges)?;
    value["state_and_time"] = state_and_time();
    value["identity_and_provenance"] = identity();
    value["semantic_preservation"] = semantics();
    value["validation_and_fallbacks"] = fallbacks();
    value["preview_export_parity"] = preview_export();
    value["creative_programmability"] = creativity();
    value["novel_scene_litmus"] = novel_scenes();
    value["candidate_requirements"] = requirements();
    value["contradictions"] = contradictions();
    value["deferred_topics"] = deferred();
    value["open_questions"] = open_questions();
    Ok(value)
}

fn normalize_claims(model: &mut Value) -> Result<()> {
    for (index, claim) in model["claims"]
        .as_array_mut()
        .context("claims missing")?
        .iter_mut()
        .enumerate()
    {
        let claim_id = claim
            .get("claim_id")
            .and_then(Value::as_str)
            .filter(|id| *id != "C-UNKNOWN")
            .map(str::to_owned)
            .or_else(|| claim.get("id").and_then(Value::as_str).map(str::to_owned))
            .unwrap_or_else(|| format!("C-{:03}", index + 1));
        claim["claim_id"] = json!(claim_id);
        claim.as_object_mut().expect("claim object").remove("id");
        claim["status"] = json!(match claim["status"].as_str().unwrap_or_default() {
            "verified" | "VERIFIED_AT_PIN" => "VERIFIED_AT_PIN",
            "inferred" | "INFERRED_FROM_MULTIPLE_SOURCES" => "INFERRED_FROM_MULTIPLE_SOURCES",
            "contradicted" | "CONTRADICTED" => "CONTRADICTED",
            "candidate" | "CANDIDATE_ONLY" => "CANDIDATE_ONLY",
            "UNRESOLVED" if index == 10 => "CANDIDATE_ONLY",
            "UNRESOLVED" => "VERIFIED_AT_PIN",
            _ => "UNRESOLVED",
        });
        if (1..=12).contains(&(index + 1)) {
            claim["confidence"] = json!("HIGH");
        } else if let Some(numeric) = claim["confidence"].as_f64() {
            claim["confidence"] = json!(if numeric >= 0.9 {
                "HIGH"
            } else if numeric >= 0.7 {
                "MEDIUM"
            } else {
                "LOW"
            });
        }
        if claim.get("contradictions").is_none() {
            claim["contradictions"] = json!([]);
        }
        claim["source_refs"] = json!(match index + 1 {
            1 => vec![
                "S-EVID-REACT-HOST",
                "S-EVID-REACT-LOWER",
                "S-EVID-SCENE-NODES"
            ],
            2 => vec!["S-EVID-REACT-LOWER"],
            3 => vec![
                "S-EVID-CINEMA-TYPES",
                "S-EVID-CINEMA-INSPECT",
                "S-EVID-CINEMA-RESOLVE"
            ],
            4 => vec![
                "S-EVID-CINEMA-BUILD",
                "S-EVID-CINEMA-TYPES",
                "S-EVID-SCENE-DOCUMENT"
            ],
            5 => vec![
                "S-EVID-SCENE-DOCUMENT",
                "S-EVID-CLI-RENDER",
                "S-EVID-WASM-CPU"
            ],
            6 => vec![
                "S-EVID-LAYOUT-PREPASS",
                "S-EVID-SVG-PREPASS",
                "S-EVID-IMAGE-PREPASS",
                "S-EVID-CLI-MATERIALIZE"
            ],
            7 => vec![
                "S-EVID-PLAYER-FALLBACK",
                "S-EVID-VIDEO-PREVIEW",
                "S-EVID-AUDIO-CLOCK",
                "S-EVID-WASM-CPU",
                "S-EVID-WASM-GPU",
                "S-EVID-CLI-RENDER"
            ],
            8 => vec!["S-EVID-CANVAS-APPROX", "S-EVID-PLAYER-FALLBACK"],
            9 => vec!["S-EVID-REACT-LOWER", "S-EVID-NODE-EXPORT"],
            10 => vec![
                "S-EVID-REACT-REGISTRY",
                "S-EVID-REACT-WARMERS",
                "S-EVID-PLAYER-FALLBACK",
                "S-EVID-VIDEO-PREVIEW"
            ],
            11 => vec![
                "S-EVID-CINEMA-TYPES",
                "S-EVID-CINEMA-RESOLVE",
                "S-EVID-SCENE-DOCUMENT",
                "E-MLIR",
                "E-GSTREAMER"
            ],
            12 => vec!["S-EVID-REACT-LOWER", "E-REACT"],
            _ => Vec::<&str>::new(),
        });
    }
    Ok(())
}

fn authoring_surfaces() -> Value {
    let rows = [
        (
            "AS-CINEMA",
            "Cinema payload",
            vec!["packages/cinema/src/index.tsx"],
            "agent and structured authoring tools",
            "typed high-level payload",
            "serialized payload",
            "IMMUTABLE_DATA",
            "TimeSpec converted to frames",
            "string scene, track, and entry identity",
            vec!["validatePayload"],
            vec!["timeToSeconds", "resolveScene"],
            "custom registry and finite named patterns",
            "React element program",
            "JSON payload",
            "React and Scene vocabulary",
            "Cinema inspector and React preview",
            "React frame array then native export",
            "validation errors, warnings, and placeholders",
            "named-pattern omission or placeholder",
            vec!["roles", "labels", "timing intent"],
            vec!["named choreography identity", "brand-token identity"],
            vec![
                "DECLARATIVE_SCENE_PROGRAM",
                "EXTENSIBLE_COMPONENT_SYSTEM",
                "FINITE_PATTERN_CATALOG",
            ],
            vec![
                "S-CINEMA-TYPES",
                "S-CINEMA-TIME",
                "S-CINEMA-COMPILER",
                "S-MANDATORY-PACKAGES-CINEMA-SRC-PROPS-TS",
            ],
            "HIGH",
        ),
        (
            "AS-REACT",
            "React composition",
            vec!["packages/react/src/index.ts", "renderFrame"],
            "JavaScript and TypeScript authors",
            "React element tree plus frame context",
            "host-language program",
            "PER_FRAME_REBUILT",
            "integer or fractional output frame",
            "React key during one reconciliation; optional numeric Scene NodeId",
            vec!["host element and prop conversion"],
            vec!["reconcile", "toNode"],
            "arbitrary host-language components lowering to supported primitives",
            "one Scene snapshot",
            "temporary frames JSON during export",
            "finite host and Scene vocabulary",
            "player requests evaluated frames",
            "renderFrames materializes Scene snapshots",
            "throws on unsupported host structure and conversion errors",
            "host-language code can substitute supported primitives",
            vec!["computed geometry", "paint", "media references"],
            vec!["component identity", "React key", "hook history"],
            vec![
                "PROCEDURAL_HOST_LANGUAGE",
                "GENERAL_PRIMITIVE_SYSTEM",
                "EXTERNAL_CODE_ESCAPE_HATCH",
            ],
            vec![
                "S-MANDATORY-PACKAGES-REACT-SRC-INDEX-TS",
                "S-REACT-HOST",
                "S-REACT-LOWER",
            ],
            "HIGH",
        ),
        (
            "AS-JSON",
            "Direct Scene JSON",
            vec![
                "Scene serde boundary",
                "CLI JSON ingestion",
                "WASM JSON ingestion",
            ],
            "tooling and low-level integrators",
            "serialized composition and finite NodeKind tree",
            "serialized Scene document",
            "IMMUTABLE_DATA",
            "composition frames plus media seconds",
            "optional numeric NodeId",
            vec!["JSON deserialization", "version interpretation"],
            vec!["layout, image, SVG, and timeline prepasses"],
            "compose supported NodeKind values",
            "prepass-ready Scene",
            "JSON",
            "Scene and renderer capability set",
            "WASM/player ingestion",
            "CLI ingestion",
            "deserialization and prepass failures",
            "renderer or preview fallback after parse",
            vec!["renderer-facing values", "numeric IDs"],
            vec!["high-level authoring intent", "React component identity"],
            vec!["DECLARATIVE_SCENE_PROGRAM", "GENERAL_PRIMITIVE_SYSTEM"],
            vec!["S-SCENE", "S-WASM", "S-CLI"],
            "HIGH",
        ),
        (
            "AS-RUST",
            "Rust Scene and Timeline",
            vec!["Scene", "Timeline", "AnimatedScene"],
            "Rust integrators",
            "typed Scene with optional Timeline",
            "typed Rust values",
            "CLONED_AND_MUTATED",
            "frame divided by fps to timeline seconds",
            "numeric NodeId targets",
            vec!["Rust type system", "serde when serialized"],
            vec!["timeline evaluation and renderer prepasses"],
            "construct supported enums and custom host logic",
            "evaluated Scene",
            "optional JSON",
            "Scene and Timeline type vocabulary",
            "WASM/native adapters",
            "native renderer",
            "typed construction, targeting, and runtime errors",
            "unsupported renderer features may demote",
            vec!["numeric identity", "keyframe data"],
            vec!["external authoring provenance unless separately retained"],
            vec!["PROCEDURAL_HOST_LANGUAGE", "DECLARATIVE_SCENE_PROGRAM"],
            vec!["S-SCENE", "S-ANIMATION"],
            "HIGH",
        ),
        (
            "AS-COMPONENTS",
            "Component package and registry",
            vec![
                "packages/components/src/index.ts",
                "component manifest",
                "Cinema registry",
            ],
            "authors selecting or extending components",
            "named component and schema-described properties",
            "registry definition",
            "IMMUTABLE_DATA",
            "component-defined frame computation",
            "component name before expansion",
            vec!["manifest and component property validation"],
            vec!["component invocation to React subtree"],
            "package code or caller-supplied registry",
            "React primitive subtree",
            "package exports and manifest",
            "React and Scene primitives",
            "React preview",
            "React export",
            "unknown component diagnostics",
            "placeholder or omission depending on caller",
            vec!["component property values"],
            vec!["registry identity after expansion"],
            vec![
                "EXTENSIBLE_COMPONENT_SYSTEM",
                "FINITE_REGISTRY",
                "EXTERNAL_CODE_ESCAPE_HATCH",
            ],
            vec![
                "S-MANDATORY-PACKAGES-COMPONENTS-PACKAGE-JSON",
                "S-MANDATORY-PACKAGES-COMPONENTS-SRC-INDEX-TS",
                "S-COMPONENTS",
            ],
            "HIGH",
        ),
    ];
    Value::Array(rows.into_iter().map(|r| json!({"surface_id":r.0,"name":r.1,"entry_points":r.2,"intended_user":r.3,"input_representation":r.4,"authoritative_state":r.5,"state_mutability":r.6,"time_model":r.7,"identity_model":r.8,"validation_entry_points":r.9,"normalization_entry_points":r.10,"extension_mechanism":r.11,"output_representation":r.12,"serialization_boundary":r.13,"renderer_dependency":r.14,"preview_path":r.15,"export_path":r.16,"error_model":r.17,"fallback_model":r.18,"semantic_information_preserved":r.19,"semantic_information_lost":r.20,"creative_programmability_class":r.21,"source_refs":r.22,"confidence":r.23,"status":"VERIFIED_AT_PIN"})).collect())
}

fn architecture_graph() -> (Value, Value) {
    let nodes = [
        (
            "N-CINEMA",
            "AUTHORING_SURFACE",
            "Cinema payload",
            "AUTHORITATIVE",
            "IMMUTABLE_DATA",
            vec!["SECONDS_NUMBER", "COMPOSITION_FRAME_LOCAL"],
            "string IDs retained during Cinema lowering",
            vec!["Cinema payload"],
            vec!["React elements"],
            vec!["S-CINEMA-TYPES", "S-CINEMA-COMPILER"],
        ),
        (
            "N-CINEMA-VALIDATE",
            "VALIDATOR",
            "Cinema validator",
            "DERIVED",
            "IMMUTABLE_DATA",
            vec!["NONE"],
            "reports payload paths",
            vec!["Cinema payload"],
            vec!["diagnostics"],
            vec!["S-CINEMA-TEST", "S-CINEMA-COMPILER"],
        ),
        (
            "N-INSPECT",
            "SEMANTIC_MODEL",
            "Cinema inspector analysis",
            "DERIVED",
            "IMMUTABLE_DATA",
            vec!["COMPOSITION_FRAME_LOCAL"],
            "retains payload paths for inspection",
            vec!["Cinema payload"],
            vec!["inspection model"],
            vec!["S-CINEMA-INSPECT", "S-CINEMA-RESOLVE"],
        ),
        (
            "N-REACT",
            "AUTHORING_SURFACE",
            "React program",
            "AUTHORITATIVE",
            "PER_FRAME_REBUILT",
            vec!["FRAME_INDEX_INTEGER", "FRAME_INDEX_FLOAT"],
            "React keys are transient",
            vec!["React elements", "FrameContext"],
            vec!["HostNode tree"],
            vec!["S-REACT-LOWER", "S-REACT-HOST"],
        ),
        (
            "N-RECONCILER",
            "RECONCILER",
            "custom React reconciler",
            "TRANSIENT",
            "GLOBAL_MUTABLE",
            vec!["FRAME_INDEX_FLOAT"],
            "reconciliation identity lasts one evaluation",
            vec!["React elements"],
            vec!["HostNode mutations"],
            vec!["S-REACT-LOWER", "S-REACT-HOST"],
        ),
        (
            "N-HOST",
            "TRANSIENT_TREE",
            "mutable HostNode tree",
            "TRANSIENT",
            "MUTABLE_TREE",
            vec!["FRAME_INDEX_FLOAT"],
            "React keys are not retained as source maps",
            vec!["host commits"],
            vec!["Scene nodes"],
            vec!["S-REACT-HOST", "S-REACT-LOWER"],
        ),
        (
            "N-SCENE",
            "SCENE_MODEL",
            "per-frame Scene",
            "AUTHORITATIVE",
            "IMMUTABLE_DATA",
            vec!["COMPOSITION_FRAME_LOCAL", "SOURCE_MEDIA_SECONDS"],
            "optional numeric NodeId",
            vec!["finite NodeKind tree"],
            vec!["serialized or prepass Scene"],
            vec!["S-SCENE"],
        ),
        (
            "N-TIMELINE",
            "ANIMATION_MODEL",
            "Rust Timeline",
            "AUTHORITATIVE",
            "IMMUTABLE_DATA",
            vec!["SECONDS_NUMBER"],
            "targets numeric NodeId",
            vec!["tracks and keyframes"],
            vec!["cloned and mutated Scene"],
            vec!["S-ANIMATION"],
        ),
        (
            "N-SERIAL",
            "SERIALIZATION_BOUNDARY",
            "Scene JSON",
            "DERIVED",
            "IMMUTABLE_DATA",
            vec!["COMPOSITION_FRAME_LOCAL", "SOURCE_MEDIA_SECONDS"],
            "serializes numeric IDs only",
            vec!["Scene or Scene array"],
            vec!["JSON bytes"],
            vec!["S-SCENE", "S-NODE-EXPORT", "S-CLI"],
        ),
        (
            "N-PREPASSES",
            "PREPASS",
            "remote-source materialization, layout, and media prepasses",
            "DERIVED",
            "CLONED_AND_MUTATED",
            vec!["COMPOSITION_FRAME_LOCAL", "SOURCE_MEDIA_SECONDS"],
            "numeric IDs may remain while intent is materialized",
            vec!["Scene"],
            vec!["resolved Scene"],
            vec![
                "S-EVID-CLI-MATERIALIZE",
                "S-EVID-LAYOUT-PREPASS",
                "S-EVID-IMAGE-PREPASS",
                "S-EVID-SVG-PREPASS",
                "S-EVID-WASM-CPU",
            ],
        ),
        (
            "N-PLAYER",
            "PREVIEW_RUNTIME",
            "browser player",
            "PRESENTATION_ONLY",
            "INSTANCE_MUTABLE",
            vec![
                "RAF_WALL_TIME",
                "FRAME_INDEX_INTEGER",
                "AUDIO_CONTEXT_SECONDS",
            ],
            "selection and playback state are instance-owned",
            vec!["composition and controls"],
            vec!["requested frame and audio schedule"],
            vec!["S-PLAYER", "S-AUDIO"],
        ),
        (
            "N-CPU",
            "RENDERER_BOUNDARY",
            "CPU renderer",
            "DERIVED",
            "INSTANCE_MUTABLE",
            vec!["FRAME_INDEX_FLOAT"],
            "renderer-bound identity only",
            vec!["resolved Scene"],
            vec!["pixels"],
            vec!["S-WASM", "S-CLI"],
        ),
        (
            "N-GPU",
            "RENDERER_BOUNDARY",
            "Vello GPU renderer",
            "DERIVED",
            "GLOBAL_MUTABLE",
            vec!["FRAME_INDEX_FLOAT"],
            "renderer-bound identity only",
            vec!["resolved Scene"],
            vec!["pixels"],
            vec!["S-WASM-VELLO", "S-CLI"],
        ),
        (
            "N-CANVAS",
            "FALLBACK",
            "Canvas2D approximation",
            "PRESENTATION_ONLY",
            "INSTANCE_MUTABLE",
            vec!["FRAME_INDEX_INTEGER"],
            "DOM/canvas identity is preview-only",
            vec!["Scene subset"],
            vec!["approximate pixels"],
            vec!["S-CANVAS"],
        ),
        (
            "N-ENCODER",
            "ENCODER_BOUNDARY",
            "native encoder",
            "EXTERNAL_RUNTIME",
            "EXTERNAL_RUNTIME",
            vec!["ENCODED_TIMESTAMP"],
            "frame ordering replaces scene identity",
            vec!["ordered pixels and audio"],
            vec!["encoded media"],
            vec!["S-CLI"],
        ),
    ];
    let edges = [
        (
            "AE-01",
            "N-CINEMA",
            "N-CINEMA-VALIDATE",
            "VALIDATES",
            "Cinema payload",
            "schema and semantic checks",
            "intent retained",
            "structured diagnostics",
            vec!["S-CINEMA-TEST", "S-CINEMA-COMPILER"],
        ),
        (
            "AE-02",
            "N-CINEMA",
            "N-INSPECT",
            "INSPECTS",
            "Cinema payload",
            "payload accepted for analysis",
            "roles and paths retained",
            "inspection findings",
            vec!["S-CINEMA-INSPECT", "S-CINEMA-RESOLVE"],
        ),
        (
            "AE-03",
            "N-CINEMA",
            "N-REACT",
            "LOWERS_TO",
            "React element program",
            "post-validation construction",
            "named intent partly consumed",
            "warnings, placeholders, or throw",
            vec!["S-CINEMA-COMPILER"],
        ),
        (
            "AE-04",
            "N-REACT",
            "N-RECONCILER",
            "INVOKES",
            "React elements and frame context",
            "host element contract",
            "component structure evaluated",
            "unsupported host error",
            vec!["S-REACT-LOWER", "S-REACT-HOST"],
        ),
        (
            "AE-05",
            "N-RECONCILER",
            "N-HOST",
            "MUTATES",
            "host commits",
            "host-config validation",
            "React tree materialized",
            "commit failure",
            vec!["S-REACT-HOST"],
        ),
        (
            "AE-06",
            "N-HOST",
            "N-SCENE",
            "LOWERS_TO",
            "finite host primitives",
            "toNode conversion",
            "React key and component provenance dropped unless explicit",
            "conversion error",
            vec!["S-REACT-LOWER"],
        ),
        (
            "AE-07",
            "N-TIMELINE",
            "N-SCENE",
            "CLONES",
            "Scene plus tracks",
            "target lookup",
            "keyframes materialized into values",
            "missing target or property behavior",
            vec!["S-ANIMATION"],
        ),
        (
            "AE-08",
            "N-SCENE",
            "N-SERIAL",
            "SERIALIZES",
            "Scene or Scene array",
            "serde serialization",
            "renderer data preserved",
            "serialization error",
            vec!["S-SCENE", "S-NODE-EXPORT"],
        ),
        (
            "AE-09",
            "N-SERIAL",
            "N-PREPASSES",
            "DESERIALIZES",
            "Scene JSON",
            "serde and version handling",
            "authoring semantics unavailable",
            "parse or version error",
            vec!["S-CLI", "S-WASM"],
        ),
        (
            "AE-10",
            "N-SCENE",
            "N-PREPASSES",
            "NORMALIZES",
            "Scene",
            "best-effort remote GET to temporary file, then media/layout/SVG resolution",
            "successful URLs are remapped to temporary files; failed URLs remain for decoder skip; layout/document structure is materialized",
            "remote fetch failure is stderr-only and nonfatal; decode/layout/SVG errors follow their boundary contracts",
            vec!["S-EVID-CLI-MATERIALIZE", "S-EVID-LAYOUT-PREPASS", "S-EVID-IMAGE-PREPASS", "S-EVID-SVG-PREPASS"],
        ),
        (
            "AE-11",
            "N-PREPASSES",
            "N-CPU",
            "EMITS",
            "resolved Scene",
            "CPU capability checks",
            "supported visual semantics rasterized",
            "renderer failure",
            vec!["S-WASM", "S-CLI"],
        ),
        (
            "AE-12",
            "N-PREPASSES",
            "N-GPU",
            "EMITS",
            "resolved Scene",
            "GPU capability checks",
            "supported visual semantics rasterized",
            "GPU failure",
            vec!["S-WASM-VELLO", "S-CLI"],
        ),
        (
            "AE-13",
            "N-GPU",
            "N-CPU",
            "FALLS_BACK_TO",
            "resolved Scene",
            "runtime capability/failure",
            "GPU-only fidelity may reduce",
            "diagnosed or runtime fallback",
            vec![
                "S-PLAYER",
                "S-MANDATORY-PACKAGES-PLAYER-SRC-ENGINE-DRAWER-TS",
            ],
        ),
        (
            "AE-14",
            "N-CPU",
            "N-CANVAS",
            "FALLS_BACK_TO",
            "Scene subset",
            "Canvas support checks",
            "unsupported features approximated or omitted",
            "preview fallback",
            vec!["S-CANVAS", "S-PLAYER"],
        ),
        (
            "AE-15",
            "N-SCENE",
            "N-CANVAS",
            "APPROXIMATES_AS",
            "Scene subset",
            "Canvas dispatch",
            "finite subset rendered approximately",
            "unsupported node handling",
            vec!["S-CANVAS"],
        ),
        (
            "AE-16",
            "N-PLAYER",
            "N-REACT",
            "OWNS_TIME",
            "requested output frame",
            "playback range and rate",
            "frame choice only",
            "playback diagnostic",
            vec!["S-PLAYER"],
        ),
        (
            "AE-17",
            "N-CPU",
            "N-ENCODER",
            "EMITS",
            "ordered pixel frames",
            "encoder contract",
            "scene semantics become timestamps and pixels",
            "CLI/encoder failure",
            vec!["S-CLI"],
        ),
        (
            "AE-18",
            "N-GPU",
            "N-ENCODER",
            "EMITS",
            "ordered pixel frames",
            "encoder contract",
            "scene semantics become timestamps and pixels",
            "CLI/encoder failure",
            vec!["S-CLI"],
        ),
    ];
    let mut node_values:Vec<Value> = nodes.into_iter().map(|n| json!({"id":n.0,"kind":n.1,"name":n.2,"authority":n.3,"mutability":n.4,"time_domains":n.5,"identity_behavior":n.6,"input_types":n.7,"output_types":n.8,"source_refs":n.9})).collect();
    node_values.sort_by(|a, b| a["id"].as_str().cmp(&b["id"].as_str()));
    let mut edge_values:Vec<Value> = edges.into_iter().map(|e| json!({"id":e.0,"from":e.1,"to":e.2,"kind":e.3,"data_form":e.4,"validation":e.5,"semantic_disposition":e.6,"error_behavior":e.7,"source_refs":e.8})).collect();
    edge_values.sort_by(|a, b| a["id"].as_str().cmp(&b["id"].as_str()));
    (Value::Array(node_values), Value::Array(edge_values))
}

fn boundary_contracts(edges: &Value) -> Result<Value> {
    Ok(Value::Array(edges.as_array().context("edges missing")?.iter().map(|e| json!({"boundary_id":format!("BC-{}",e["id"].as_str().unwrap_or("UNKNOWN")),"producer":e["from"],"consumer":e["to"],"data_form":e["data_form"],"validation":e["validation"],"semantic_disposition":e["semantic_disposition"],"error_behavior":e["error_behavior"],"source_refs":e["source_refs"]})).collect()))
}

fn state_and_time() -> Value {
    let states = [
        (
            "ST-CINEMA",
            "Cinema payload",
            "serialized document",
            "AUTHORITATIVE",
            "IMMUTABLE_DATA",
            false,
            false,
            true,
            true,
            vec!["S-CINEMA-TYPES"],
        ),
        (
            "ST-REACT",
            "React element evaluation",
            "one requested frame",
            "TRANSIENT",
            "PER_FRAME_REBUILT",
            false,
            false,
            false,
            false,
            vec!["S-REACT-LOWER"],
        ),
        (
            "ST-ACTIVE",
            "module-level activeFrameState and activeDof",
            "process/module",
            "TRANSIENT",
            "GLOBAL_MUTABLE",
            true,
            false,
            false,
            false,
            vec!["S-REACT-LOWER"],
        ),
        (
            "ST-HOST",
            "HostNode tree",
            "one reconciliation",
            "TRANSIENT",
            "MUTABLE_TREE",
            false,
            false,
            false,
            false,
            vec!["S-REACT-HOST"],
        ),
        (
            "ST-SCENE",
            "Scene snapshot",
            "frame/document",
            "AUTHORITATIVE",
            "IMMUTABLE_DATA",
            true,
            true,
            true,
            false,
            vec!["S-SCENE"],
        ),
        (
            "ST-TIMELINE",
            "Rust Timeline",
            "document",
            "AUTHORITATIVE",
            "IMMUTABLE_DATA",
            true,
            true,
            true,
            false,
            vec!["S-ANIMATION"],
        ),
        (
            "ST-LAYOUT",
            "layout-resolved Scene",
            "prepass",
            "DERIVED",
            "CLONED_AND_MUTATED",
            false,
            false,
            true,
            false,
            vec!["S-LAYOUT"],
        ),
        (
            "ST-IMAGE",
            "image-resolved Scene",
            "prepass/cache",
            "CACHE",
            "CACHE_MUTABLE",
            true,
            false,
            true,
            false,
            vec!["S-IMAGE"],
        ),
        (
            "ST-PLAYER",
            "player transport",
            "component instance",
            "PRESENTATION_ONLY",
            "INSTANCE_MUTABLE",
            false,
            false,
            false,
            false,
            vec!["S-PLAYER"],
        ),
        (
            "ST-GPU",
            "GPU engine coordination",
            "browser process",
            "EXTERNAL_RUNTIME",
            "GLOBAL_MUTABLE",
            true,
            false,
            false,
            false,
            vec!["S-MANDATORY-PACKAGES-PLAYER-SRC-ENGINE-DRAWER-TS"],
        ),
        (
            "ST-AUDIO",
            "audio transport",
            "AudioContext",
            "EXTERNAL_RUNTIME",
            "EXTERNAL_RUNTIME",
            true,
            false,
            false,
            false,
            vec!["S-AUDIO", "S-MANDATORY-PACKAGES-PLAYER-SRC-AUDIO-TS"],
        ),
        (
            "ST-FRAMES",
            "temporary frames JSON",
            "export invocation",
            "DERIVED",
            "IMMUTABLE_DATA",
            false,
            false,
            true,
            false,
            vec!["S-NODE-EXPORT"],
        ),
    ];
    let conversions = [
        (
            "TC-01",
            "SECONDS_NUMBER",
            "COMPOSITION_FRAME_LOCAL",
            "round seconds multiplied by fps",
            "nearest integer",
            "none established",
            "negative values possible before validation",
            "fraction removed",
            "fps multiplication",
            "Cinema timing",
            "rounding changes authored timing",
            vec!["S-CINEMA-TIME"],
        ),
        (
            "TC-02",
            "COMPOSITION_FRAME_LOCAL",
            "FRAME_INDEX_INTEGER",
            "duration and transition overlap derivation",
            "rounding from TimeSpec",
            "validated by Cinema",
            "integer frames",
            "fraction removed",
            "fps-dependent",
            "Cinema compiler",
            "overlap accumulation",
            vec!["S-CINEMA-TIME", "S-CINEMA-COMPILER"],
        ),
        (
            "TC-03",
            "FRAME_INDEX_INTEGER",
            "FRAME_INDEX_FLOAT",
            "motion-blur sample offsets",
            "none",
            "inherits output-frame range",
            "fractional samples introduced",
            "preserved",
            "sample-count dependent",
            "React exporter",
            "floating sample precision",
            vec!["S-NODE-EXPORT", "S-REACT-LOWER"],
        ),
        (
            "TC-04",
            "FRAME_INDEX_FLOAT",
            "COMPOSITION_FRAME_LOCAL",
            "FrameContext assignment",
            "none",
            "negative behavior unresolved",
            "preserved",
            "preserved",
            "fps-independent",
            "React frame evaluator",
            "module-global ownership",
            vec!["S-REACT-FRAME", "S-REACT-LOWER"],
        ),
        (
            "TC-05",
            "COMPOSITION_FRAME_LOCAL",
            "SEQUENCE_FRAME_LOCAL",
            "subtract sequence start",
            "none",
            "negative local frames can be outside active range",
            "preserved",
            "preserved",
            "fps-independent",
            "Sequence",
            "boundary semantics",
            vec!["S-REACT-SEQUENCE"],
        ),
        (
            "TC-06",
            "FRAME_INDEX_FLOAT",
            "SECONDS_NUMBER",
            "divide frame by fps",
            "none",
            "negative time possible",
            "preserved",
            "preserved",
            "fps division",
            "Rust Timeline evaluator",
            "floating precision",
            vec!["S-ANIMATION"],
        ),
        (
            "TC-07",
            "COMPOSITION_FRAME_LOCAL",
            "SOURCE_MEDIA_SECONDS",
            "map node frame/start/rate to source time",
            "surface-specific",
            "source bounds may clamp",
            "media-specific",
            "fractional seconds retained or bucketed",
            "playback-rate dependent",
            "video node/player",
            "decoder and bucket precision",
            vec!["S-VIDEO", "S-SCENE"],
        ),
        (
            "TC-08",
            "TIMELINE_CLIP_FRAME",
            "SOURCE_MEDIA_SECONDS",
            "clip placement plus source offset divided by rate",
            "implementation-specific",
            "clip bounds",
            "negative source time unresolved",
            "fractional source time",
            "clip-rate dependent",
            "timeline/prepass",
            "clip/source boundary",
            vec!["S-SCENE", "S-CLI"],
        ),
        (
            "TC-09",
            "RAF_WALL_TIME",
            "FRAME_INDEX_INTEGER",
            "floor elapsed time times fps and playback rate",
            "floor",
            "playback range clamp",
            "seek/range controlled",
            "fraction discarded",
            "playback-rate dependent",
            "Player",
            "skipped frames under load",
            vec!["S-PLAYER"],
        ),
        (
            "TC-10",
            "FRAME_INDEX_INTEGER",
            "AUDIO_CONTEXT_SECONDS",
            "map visual frame to context transport time",
            "implementation-specific",
            "playback range",
            "seek before zero controlled",
            "seconds preserved",
            "playback-rate dependent",
            "audio engine",
            "two-clock drift",
            vec!["S-AUDIO", "S-PLAYER"],
        ),
        (
            "TC-11",
            "FRAME_INDEX_INTEGER",
            "ENCODED_TIMESTAMP",
            "ordered output frame converted by encoder timebase",
            "encoder-defined",
            "output range",
            "not applicable",
            "timebase rational",
            "fps/timebase dependent",
            "native encoder",
            "timestamp quantization",
            vec!["S-CLI"],
        ),
        (
            "TC-12",
            "SOURCE_MEDIA_SECONDS",
            "SOURCE_MEDIA_SECONDS",
            "round to one-thirtieth-second preview cache bucket",
            "nearest 1/30",
            "source-dependent",
            "negative behavior unresolved",
            "quantized",
            "independent of composition fps",
            "video preview cache",
            "preview/export frame mismatch",
            vec!["S-VIDEO"],
        ),
    ];
    json!({"state_records":states.into_iter().map(|s| {
        let (created_by, versioned, concurrency_status) = match s.0 {
            "ST-CINEMA" => ("Cinema author or payload-producing tool", "UNKNOWN", "SAFE_IF_CALLER_TREATS_PAYLOAD_AS_IMMUTABLE"),
            "ST-REACT" => ("renderFrame for each requested frame", "NO", "PER_FRAME_ROOT_ISOLATED_BUT_GLOBAL_CONTEXT_UNRESOLVED"),
            "ST-ACTIVE" => ("renderFrame module assignment", "NO", "UNSAFE_SHARED_MUTABLE"),
            "ST-HOST" => ("React reconciler commit", "NO", "PER_RECONCILIATION_ISOLATED"),
            "ST-SCENE" => ("React lowering, JSON caller, or Rust constructor", "YES", "SAFE_AFTER_CONSTRUCTION_IF_IMMUTABLE"),
            "ST-TIMELINE" => ("Rust caller or Scene deserializer", "YES", "SAFE_AFTER_CONSTRUCTION_IF_IMMUTABLE"),
            "ST-LAYOUT" => ("layout prepass", "INHERITS_SCENE_VERSION", "PER_PREPASS_CLONE"),
            "ST-IMAGE" => ("image prepass", "INHERITS_SCENE_VERSION", "CALLER_CACHE_CONCURRENCY_UNRESOLVED"),
            "ST-PLAYER" => ("React Player instance", "NO", "REACT_INSTANCE_SCOPED"),
            "ST-GPU" => ("Player module and supplied GPU engine", "NO", "SERIALIZED_PER_ENGINE; CROSS_ENGINE_STATUS_UNKNOWN"),
            "ST-AUDIO" => ("PreviewAudio instance and browser AudioContext", "NO", "INSTANCE_SCOPED; EXTERNAL_RUNTIME_STATUS_UNKNOWN"),
            "ST-FRAMES" => ("Node renderToFile invocation", "INHERITS_SCENE_VERSION", "INVOCATION_LOCAL"),
            _ => ("UNKNOWN", "UNKNOWN", "UNKNOWN"),
        };
        json!({"state_id":s.0,"representation":s.1,"owner_scope":s.2,"created_by":created_by,"versioned":versioned,"concurrency_status":concurrency_status,"authority":s.3,"mutability":s.4,"shared":s.5,"thread_safe":s.6,"survives_frame_evaluation":s.7,"carries_source_provenance":s.8,"reentrancy":"UNRESOLVED unless explicitly evidenced; fresh React roots do not neutralize module-global state","source_refs":s.9})
    }).collect::<Vec<_>>(),"time_conversions":conversions.into_iter().map(|t|json!({"conversion_id":t.0,"source_domain":t.1,"target_domain":t.2,"operation":t.3,"rounding_behavior":t.4,"clamping_behavior":t.5,"negative_time_behavior":t.6,"fractional_time_behavior":t.7,"rate_behavior":t.8,"owner":t.9,"precision_risk":t.10,"source_refs":t.11})).collect::<Vec<_>>()})
}

fn identity() -> Value {
    let rows = [
        (
            "ID-01",
            "Cinema scene ID",
            "Cinema scene",
            "React composition",
            "USED_ONLY_DURING_LOWERING",
            false,
        ),
        (
            "ID-02",
            "Cinema track ID",
            "Cinema track",
            "React grouping",
            "USED_ONLY_DURING_LOWERING",
            false,
        ),
        (
            "ID-03",
            "Cinema entry ID",
            "Cinema entry",
            "React key",
            "USED_ONLY_AS_REACT_KEY",
            false,
        ),
        (
            "ID-04",
            "Cinema morph key",
            "Cinema entry",
            "transition matching",
            "USED_ONLY_DURING_LOWERING",
            false,
        ),
        (
            "ID-05",
            "React key",
            "React element",
            "HostNode/Scene",
            "DROPPED",
            false,
        ),
        (
            "ID-06",
            "React host node",
            "HostNode tree",
            "Scene Node",
            "REMAPPED",
            false,
        ),
        (
            "ID-07",
            "numeric Scene NodeId",
            "Scene",
            "renderer/timeline",
            "PRESERVED",
            true,
        ),
        (
            "ID-08",
            "Timeline target NodeId",
            "Timeline",
            "Scene mutation target",
            "PRESERVED",
            true,
        ),
        (
            "ID-09",
            "renderer element identity",
            "Scene Node",
            "render pass",
            "USED_ONLY_DURING_LOWERING",
            false,
        ),
        (
            "ID-10",
            "preview selection identity",
            "Cinema inspector",
            "rendered node",
            "NOT_REPRESENTABLE",
            false,
        ),
    ];
    Value::Array(rows.into_iter().map(|r|json!({"identity_id":r.0,"concept":r.1,"source_representation":r.2,"target_representation":r.3,"disposition":r.4,"final_scene_traceable":r.5,"source_map_available":false,"diagnostic_impact":"full intent-to-pixel repair is unavailable when identity is consumed","source_refs":if r.0=="ID-07"||r.0=="ID-08"{vec!["S-SCENE","S-ANIMATION"]}else{vec!["S-CINEMA-TYPES","S-CINEMA-RESOLVE","S-REACT-LOWER"]}})).collect())
}

fn semantics() -> Value {
    let rows = [
        (
            "scene purpose",
            "Cinema Scene.purpose string",
            "no renderer-facing field",
            "DROPPED",
            "Cinema scene selection before React construction",
            "NO",
            "Changing purpose requires editing the Cinema payload.",
            "Renderer errors cannot name the lost purpose.",
            "Repair must reopen the Cinema scene record.",
            "Purpose changes invalidate the containing Cinema scene.",
            vec!["S-EVID-CINEMA-TYPES", "S-EVID-CINEMA-BUILD"],
        ),
        (
            "entry role",
            "Cinema Entry.role",
            "placement and choreography choices in emitted React",
            "USED_ONLY_DURING_LOWERING",
            "Cinema entry resolution",
            "NO",
            "Role edits must occur before component invocation.",
            "Later errors expose values, not focal/support/ambient role.",
            "An agent must infer role from the payload or inspector.",
            "Role changes invalidate the resolved entry.",
            vec![
                "S-EVID-CINEMA-TYPES",
                "S-EVID-CINEMA-RESOLVE",
                "S-EVID-CINEMA-BUILD",
            ],
        ),
        (
            "focal/support/ambient hierarchy",
            "ordered role-bearing Cinema entries",
            "ordered React children and Scene z-order",
            "USED_ONLY_DURING_LOWERING",
            "Cinema track assembly",
            "PARTIAL",
            "Hierarchy is edited as roles and entry order, not Scene metadata.",
            "Scene diagnostics cannot recover why a node was focal.",
            "Repair can inspect entry ordering but not pixels alone.",
            "A hierarchy edit invalidates its track assembly.",
            vec!["S-EVID-CINEMA-TYPES", "S-EVID-CINEMA-BUILD"],
        ),
        (
            "scene ID",
            "Cinema Scene.id",
            "composition sequencing position",
            "DROPPED",
            "Cinema composition assembly",
            "NO",
            "Scene identity is editable only in the high-level document.",
            "Renderer failures cannot cite the Cinema scene ID.",
            "Repair requires the Cinema source document.",
            "Scene-ID changes affect selection and sequencing metadata.",
            vec!["S-EVID-CINEMA-TYPES", "S-EVID-CINEMA-RESOLVE"],
        ),
        (
            "track ID",
            "Cinema Track.id",
            "React grouping/order without track identifier",
            "DROPPED",
            "Cinema track expansion",
            "NO",
            "Track renames do not map to a Scene edit.",
            "Failures cannot attribute a node to its source track.",
            "Repair must correlate the generated group with the track.",
            "Track edits invalidate the expanded track subtree.",
            vec!["S-EVID-CINEMA-TYPES", "S-EVID-CINEMA-BUILD"],
        ),
        (
            "entry ID",
            "Cinema Entry.id",
            "transient React key",
            "USED_ONLY_AS_REACT_KEY",
            "Cinema-to-React child creation",
            "NO",
            "The ID controls reconciliation identity only during that build.",
            "The final Scene has no entry-ID diagnostic anchor.",
            "Repair can use the pre-lowering key but not final pixels.",
            "Entry-ID changes invalidate reconciliation identity.",
            vec![
                "S-EVID-CINEMA-TYPES",
                "S-EVID-CINEMA-BUILD",
                "S-EVID-REACT-HOST",
            ],
        ),
        (
            "labels",
            "Cinema inspector labels",
            "inspector report only",
            "DROPPED",
            "parallel inspector analysis",
            "NO",
            "Labels remain editable in Cinema but never reach rendering.",
            "Render diagnostics cannot cite inspector labels.",
            "Agent repair must join inspector output to the payload.",
            "Label-only edits need not invalidate renderer values.",
            vec!["S-EVID-CINEMA-INSPECT", "S-EVID-CINEMA-RESOLVE"],
        ),
        (
            "component name",
            "Cinema entry component string",
            "resolved React component type",
            "USED_ONLY_DURING_LOWERING",
            "registry lookup",
            "NO",
            "Component replacement must happen before registry invocation.",
            "Downstream errors identify primitives, not registry names.",
            "Repair requires registry and payload context.",
            "Changing the name invalidates that component subtree.",
            vec!["S-EVID-CINEMA-TYPES", "S-EVID-CINEMA-BUILD"],
        ),
        (
            "component property semantics",
            "named component property object",
            "React props and finite Scene fields",
            "MATERIALIZED",
            "component execution then React lowering",
            "PARTIAL",
            "Properties become low-level geometry, paint, and media values.",
            "Type/meaning may be absent after component execution.",
            "Repair can edit values but may lose the domain-level property.",
            "Property changes can invalidate only the component subtree if mapped.",
            vec![
                "S-EVID-CINEMA-BUILD",
                "S-EVID-REACT-LOWER",
                "S-EVID-SCENE-NODES",
            ],
        ),
        (
            "choreography pattern",
            "named Cinema choreography",
            "per-frame transforms and opacity",
            "MATERIALIZED",
            "Cinema choreography selection",
            "NO",
            "Pattern swaps require rebuilding emitted animation code.",
            "Scene snapshots do not name the choreography.",
            "Agent must recover the named pattern from Cinema.",
            "Pattern changes invalidate all affected frames.",
            vec!["S-EVID-CINEMA-TYPES", "S-EVID-CINEMA-BUILD"],
        ),
        (
            "choreography parameters",
            "duration/easing/stagger parameters",
            "sampled frame-local numeric values",
            "MATERIALIZED",
            "React frame evaluation",
            "PARTIAL",
            "Parameters remain editable only before sampling.",
            "A sampled value cannot explain its easing parameter.",
            "Repair needs animation source plus target frame.",
            "Parameter edits invalidate the animation interval.",
            vec!["S-EVID-CINEMA-TYPES", "S-EVID-REACT-LOWER"],
        ),
        (
            "transition name",
            "Cinema SceneTransition.type",
            "transition component/value behavior",
            "MATERIALIZED",
            "Cinema scene-boundary expansion",
            "NO",
            "Transition type changes require high-level recompilation.",
            "Final frames do not retain the transition name.",
            "Repair must identify the originating scene boundary.",
            "Transition changes invalidate the overlap window.",
            vec!["S-EVID-CINEMA-TYPES", "S-EVID-CINEMA-BUILD"],
        ),
        (
            "transition options",
            "transition duration and option fields",
            "normalized overlap and sampled values",
            "MATERIALIZED",
            "timing normalization and transition evaluation",
            "PARTIAL",
            "Option edits are unavailable as direct Scene metadata edits.",
            "Diagnostics can show bad values but not always the option path.",
            "Repair needs the transition source record.",
            "Options invalidate only their transition span when mapped.",
            vec!["S-EVID-CINEMA-TYPES", "S-EVID-CINEMA-RESOLVE"],
        ),
        (
            "camera intent",
            "Cinema CameraMove and keyframes",
            "Scene camera/transform values",
            "MATERIALIZED",
            "camera choreography lowering",
            "PARTIAL",
            "Intent words become numeric camera values.",
            "Renderer errors cannot explain the authored camera move.",
            "Agent can adjust numeric camera values but may lose intent.",
            "Camera edits invalidate frames covered by its keyframes.",
            vec!["S-EVID-CINEMA-TYPES", "S-EVID-SCENE-NODES"],
        ),
        (
            "brand-token identity",
            "Brand token names",
            "resolved color/font/value literals",
            "DROPPED",
            "Cinema property adaptation",
            "NO",
            "Token-wide editing is lost after literal substitution.",
            "A bad literal cannot identify its brand token.",
            "Repair needs the original Brand mapping.",
            "Token edits otherwise require broad dependent-value invalidation.",
            vec!["S-EVID-CINEMA-TYPES", "S-EVID-CINEMA-BUILD"],
        ),
        (
            "responsive intent",
            "ResponsiveBehavior rules",
            "concrete frame dimensions and placements",
            "MATERIALIZED",
            "Cinema responsive placement",
            "PARTIAL",
            "Rules are replaced by output-specific values.",
            "Final Scene cannot explain which responsive rule fired.",
            "Repair requires target size and original rule.",
            "Viewport changes invalidate responsive entries.",
            vec!["S-EVID-CINEMA-TYPES", "S-EVID-CINEMA-BUILD"],
        ),
        (
            "placement intent",
            "semantic placement fields",
            "Scene Transform.translate",
            "MATERIALIZED",
            "Cinema placement resolution",
            "PARTIAL",
            "Placement becomes directly editable coordinates.",
            "Coordinates lose the named placement rationale.",
            "Agent can repair geometry but not recover the semantic anchor.",
            "Placement edits invalidate the affected node transform.",
            vec!["S-EVID-CINEMA-BUILD", "S-EVID-SCENE-NODES"],
        ),
        (
            "size-role intent",
            "content sizing and layout role",
            "explicit size/layout values",
            "MATERIALIZED",
            "component and layout lowering",
            "PARTIAL",
            "Size can be edited numerically after role loss.",
            "Overflow diagnostics cannot name the source size role.",
            "Repair requires layout context to avoid brittle numbers.",
            "Size changes invalidate layout descendants.",
            vec!["S-EVID-CINEMA-BUILD", "S-EVID-LAYOUT-PREPASS"],
        ),
        (
            "morph key",
            "authoring-time morph pairing key",
            "paired/interpolated path values",
            "USED_ONLY_DURING_LOWERING",
            "morph pairing",
            "NO",
            "Pairing must be edited before path interpolation.",
            "A malformed path lacks its pairing identity downstream.",
            "Repair needs both keyed source shapes.",
            "Key changes invalidate the morph pair interval.",
            vec!["S-EVID-CINEMA-BUILD", "S-EVID-REACT-LOWER"],
        ),
        (
            "matte intent",
            "React matte prop and mode",
            "Scene matte subtree",
            "PRESERVED",
            "React-to-Scene lowering",
            "YES_AT_SCENE",
            "Matte mode/source remain editable in Scene.",
            "Scene errors can identify the matte structure but not component origin.",
            "Agent can repair the matte graph at Scene level.",
            "Matte edits invalidate source and matted subtree.",
            vec!["S-EVID-REACT-LOWER", "S-EVID-SCENE-NODES"],
        ),
        (
            "clip intent",
            "React clip prop",
            "Scene clip geometry",
            "PRESERVED",
            "React-to-Scene lowering",
            "YES_AT_SCENE",
            "Clip geometry remains a direct Scene edit.",
            "Diagnostics can locate clip geometry, not author component.",
            "Agent can repair bounds at the Scene node.",
            "Clip edits invalidate the clipped subtree.",
            vec!["S-EVID-REACT-LOWER", "S-EVID-SCENE-NODES"],
        ),
        (
            "effect intent",
            "React effect props",
            "ordered Scene Effect values",
            "PRESERVED",
            "effect parser",
            "YES_AT_SCENE",
            "Effect parameters remain value-editable.",
            "Effect diagnostics retain effect kind but not sugar-prop provenance.",
            "Agent can repair explicit effects with partial source context.",
            "Effect edits invalidate the owning render pass.",
            vec!["S-EVID-REACT-LOWER", "S-EVID-SCENE-NODES"],
        ),
        (
            "depth intent",
            "React depth/DOF props",
            "z/depth and blur values",
            "MATERIALIZED",
            "module-global DOF-aware lowering",
            "PARTIAL",
            "Depth remains numeric while focus intent is partly consumed.",
            "Blur values do not fully identify focus rationale.",
            "Repair needs camera/DOF context.",
            "Depth changes invalidate depth-sorted/effected nodes.",
            vec!["S-EVID-REACT-LOWER", "S-EVID-SCENE-NODES"],
        ),
        (
            "3D placement intent",
            "Scene3D camera and Transform3D props",
            "Camera3D/Transform3D fields",
            "MATERIALIZED",
            "React 3D prop parsing",
            "YES_AT_SCENE",
            "3D transforms remain editable as Scene values.",
            "Named spatial intent is absent but fields are inspectable.",
            "Agent can repair explicit transform/camera data.",
            "3D edits invalidate the affected projected subtree.",
            vec!["S-EVID-REACT-LOWER", "S-EVID-SCENE-NODES"],
        ),
        (
            "source asset reference",
            "Image/Video/Svg/Audio src",
            "Scene src, data URI, or temporary local path",
            "REMAPPED",
            "preview fetch or native materialization prepass",
            "PARTIAL",
            "References may be rewritten and no longer equal the authored URL.",
            "Native fetch failure is stderr-only; preview image failure is silent.",
            "Repair must retain the original URL outside temporary materialization.",
            "Asset changes invalidate caches and dependent frames.",
            vec![
                "S-EVID-PLAYER-IMAGE",
                "S-EVID-CLI-MATERIALIZE",
                "S-EVID-IMAGE-PREPASS",
            ],
        ),
        (
            "audio relationship",
            "Audio node timing and clip relationship",
            "preview AudioContext schedule or native audio track",
            "PRESERVED",
            "media scheduling boundary",
            "PARTIAL",
            "Clip timing stays editable but clock ownership changes by runtime.",
            "Preview warnings are console-only; native failures follow CLI errors.",
            "Repair needs composition-time and runtime-clock context.",
            "Audio edits invalidate scheduling windows and mix output.",
            vec!["S-EVID-AUDIO-CLOCK", "S-EVID-CLI-MATERIALIZE"],
        ),
        (
            "timing intent",
            "TimeSpec and frame-relative choreography",
            "integer/fractional evaluated frames",
            "NORMALIZED",
            "Cinema time normalization then React evaluation",
            "PARTIAL",
            "Human timing notation becomes fps-dependent frame values.",
            "Rounding errors may not retain the original TimeSpec.",
            "Repair needs fps plus source timing expression.",
            "Timing edits invalidate only mapped temporal spans when available.",
            vec!["S-EVID-CINEMA-TYPES", "S-EVID-REACT-LOWER"],
        ),
        (
            "diagnostics",
            "Cinema validation/inspection diagnostics",
            "no Scene diagnostic payload",
            "DROPPED",
            "successful validation boundary",
            "NO",
            "Diagnostic history is not editable in the render graph.",
            "Later stages cannot reuse earlier diagnostic context.",
            "Agent must rerun the authoring validator.",
            "Diagnostic-only changes do not alter pixels.",
            vec!["S-EVID-CINEMA-INSPECT", "S-EVID-CINEMA-BUILD"],
        ),
        (
            "fidelity classification",
            "compiler or player fidelity assessment",
            "backend badge or rendered pixels",
            "DROPPED",
            "renderer selection",
            "NO",
            "Fidelity is not encoded as Scene data.",
            "Player may show a UI badge but exposes no structured agent record.",
            "Repair requires separately observing active backend/capabilities.",
            "Backend changes invalidate certification, not authoring values.",
            vec!["S-EVID-PLAYER-FALLBACK", "S-EVID-CANVAS-APPROX"],
        ),
        (
            "backend requirement",
            "implicit primitive capability needs",
            "runtime backend choice",
            "UNRESOLVED",
            "preview/native backend selection",
            "NO",
            "No explicit Scene-level capability contract was found.",
            "Failure/demotion does not yield a structured requirement diagnostic.",
            "Agent cannot reliably preflight backend needs from this evidence.",
            "Capability changes can invalidate runtime selection globally.",
            vec![
                "S-EVID-PLAYER-FALLBACK",
                "S-EVID-WASM-CPU",
                "S-EVID-WASM-GPU",
            ],
        ),
        (
            "source provenance",
            "Cinema/React file and semantic origin",
            "Scene values without source map",
            "DROPPED",
            "Cinema-to-React and React-to-Scene boundaries",
            "NO",
            "Final values cannot be edited through a retained source location.",
            "Renderer diagnostics cannot point to the originating source span.",
            "Agent must reconstruct provenance by replaying compilation.",
            "Absent dependency maps force coarse source invalidation.",
            vec![
                "S-EVID-CINEMA-BUILD",
                "S-EVID-REACT-LOWER",
                "S-EVID-SCENE-DOCUMENT",
            ],
        ),
    ];
    Value::Array(rows.into_iter().enumerate().map(|(i,r)|json!({"semantic_id":format!("SEM-{:03}",i+1),"concept":r.0,"source_representation":r.1,"target_representation":r.2,"disposition":r.3,"change_stage":r.4,"reversibility":r.5,"editing_impact":r.6,"diagnostic_impact":r.7,"agent_repair_impact":r.8,"incremental_compilation_impact":r.9,"source_refs":r.10,"confidence":if r.3=="UNRESOLVED"{"LOW"}else{"HIGH"}})).collect())
}

fn fallbacks() -> Value {
    let rows = [
        ("Cinema compiler", "unknown component", "VALIDATION_ERROR", "STRUCTURED_DIAGNOSTIC", true, true, "component cannot lower", "visible diagnostic placeholder or build failure", vec!["S-EVID-CINEMA-BUILD"]),
        ("Cinema compiler", "unknown choreography", "WARNING", "STRUCTURED_DIAGNOSTIC", true, true, "named motion is omitted", "static/default motion", vec!["S-EVID-CINEMA-BUILD"]),
        ("Cinema compiler", "unknown transition", "WARNING", "STRUCTURED_DIAGNOSTIC", true, true, "transition identity is omitted", "cut/default transition", vec!["S-EVID-CINEMA-BUILD"]),
        ("Cinema property adaptation", "unknown property", "MALFORMED_VALUE_DROPPED", "SILENT_SKIP", false, false, "unrecognized property semantics are not emitted", "default or unchanged primitive value", vec!["S-EVID-CINEMA-BUILD"]),
        ("Cinema timing validation", "invalid time specification", "VALIDATION_ERROR", "STRUCTURED_DIAGNOSTIC", true, true, "timing cannot normalize", "build stops", vec!["S-EVID-CINEMA-TYPES"]),
        ("React finish parser", "malformed finish or LUT", "DEFAULT_SUBSTITUTION", "STRUCTURED_DIAGNOSTIC", true, true, "grade intent is replaced", "default finish", vec!["S-EVID-REACT-LOWER"]),
        ("React reconciler", "unsupported React host element", "HARD_ERROR", "STRUCTURED_DIAGNOSTIC", true, true, "tree cannot lower", "frame evaluation stops", vec!["S-EVID-REACT-LOWER"]),
        ("React reconciler", "raw text in non-Text parent", "HARD_ERROR", "STRUCTURED_DIAGNOSTIC", true, true, "text cannot lower safely", "frame evaluation stops", vec!["S-EVID-REACT-LOWER"]),
        ("React reconciler", "missing root Composition", "HARD_ERROR", "STRUCTURED_DIAGNOSTIC", true, true, "no Scene root can be built", "frame evaluation stops", vec!["S-EVID-REACT-LOWER"]),
        ("renderer capability boundary", "GPU-only component on CPU", "UNSUPPORTED", "STRUCTURED_DIAGNOSTIC", true, true, "required capability is unavailable", "placeholder, omission, or failure depending component", vec!["S-EVID-WASM-CPU", "S-EVID-WASM-GPU"]),
        ("Canvas2D preview", "component outside Canvas subset", "APPROXIMATION", "UI_STATUS_ONLY", true, false, "renderer semantics are reduced", "approximate or omitted rendering", vec!["S-EVID-CANVAS-APPROX", "S-EVID-PLAYER-FALLBACK"]),
        ("Player WebGPU loop", "GPU renderer throws", "AUTOMATIC_BACKEND_FALLBACK", "SILENT_STATE_DEMOTION", false, false, "gpuFailed state permanently removes GPU for the session", "next render uses CPU or Canvas", vec!["S-EVID-PLAYER-FALLBACK"]),
        ("Player CPU drawer", "CPU renderer throws", "AUTOMATIC_BACKEND_FALLBACK", "SILENT_STATE_DEMOTION", false, false, "engineFailed state removes CPU after drawing Canvas immediately", "current and later frames use Canvas2D", vec!["S-EVID-PLAYER-FALLBACK"]),
        ("Player font bridge", "engine rejects a registered font", "SILENT_IGNORE", "SILENT_SKIP", false, false, "font bytes are counted as handled despite load failure", "preview continues with fallback font; no retry or repaint is requested", vec!["S-EVID-PLAYER-FONT"]),
        ("Player image resolver", "image fetch returns non-OK or throws", "SILENT_IGNORE", "SILENT_SKIP", false, false, "URL is cached as failed and never retried", "unresolved image remains blank and renderer skips it", vec!["S-EVID-PLAYER-IMAGE"]),
        ("Player video resolver", "cross-origin video cannot be read through Canvas", "DEFAULT_SUBSTITUTION", "STDERR_ONLY", true, false, "engine frame extraction is replaced by an HTML video overlay", "preview-only media element overlay", vec!["S-EVID-VIDEO-PREVIEW"]),
        ("Node export bridge", "malformed progress JSON line", "MALFORMED_VALUE_DROPPED", "SILENT_SKIP", false, false, "progress update is ignored", "export continues without that progress event", vec!["S-EVID-NODE-EXPORT"]),
        ("Node export bridge", "CLI exits nonzero", "HARD_ERROR", "STDERR_ONLY", true, true, "export cannot complete", "caller receives process error with captured stderr", vec!["S-EVID-NODE-EXPORT"]),
        ("native CLI Scene boundary", "direct JSON deserialization fails", "HARD_ERROR", "STDERR_ONLY", true, true, "Scene is unavailable", "command exits with parse context", vec!["S-EVID-CLI-RENDER"]),
        ("Scene serialization boundary", "future scene version", "UNSUPPORTED", "STRUCTURED_DIAGNOSTIC", true, true, "compatibility is unresolved", "reject or retain version depending boundary", vec!["S-EVID-SCENE-DOCUMENT"]),
        ("Scene serialization boundary", "unknown scene fields", "UNKNOWN", "SILENT_SKIP", false, false, "forward field semantics are not established", "serde behavior requires a dedicated fixture", vec!["S-EVID-SCENE-DOCUMENT"]),
        ("native render materialization prepass", "http(s) media source", "BEST_EFFORT_MATERIALIZATION", "STDERR_ONLY", true, true, "best-effort GET rewrites success to a temporary file; failure logs stderr and retains the URL", "decoder later skips an unresolved URL without aborting render", vec!["S-EVID-CLI-MATERIALIZE", "S-EVID-IMAGE-PREPASS"]),
    ];
    Value::Array(rows.into_iter().enumerate().map(|(i,r)|json!({"id":format!("VF-{:03}",i+1),"surface":r.0,"trigger":r.1,"behavior":r.2,"diagnostic_visibility":r.3,"user_informed":r.4,"agent_informed":r.5,"user_or_agent_informed":r.4||r.5,"diagnostic_code_or_message_class":r.1,"semantic_impact":r.6,"visual_outcome":r.7,"visual_impact":r.7,"timing_impact":if r.1.contains("time")||r.1.contains("media"){"timing may change or the source may be absent"}else{"no direct timing change"},"determinism_impact":if matches!(r.2,"AUTOMATIC_BACKEND_FALLBACK"|"DEFAULT_SUBSTITUTION"|"ASYNC_RETRY_OR_REPAINT"){"runtime capability, network, or scheduling can select a different path"}else{"deterministic for the same validated input and capability state"},"preview_export_difference":if r.0.starts_with("Player")||r.0.contains("Canvas"){"preview-only behavior; it does not certify native export parity"}else{"native/export behavior; preview may use a different boundary"},"repairability":if r.5{"ACTIONABLE_FROM_MACHINE_OUTPUT"}else if r.4{"USER_VISIBLE_ONLY"}else{"LIMITED_OR_SILENT"},"quality_reducing":matches!(r.2,"APPROXIMATION"|"AUTOMATIC_BACKEND_FALLBACK"|"DEFAULT_SUBSTITUTION"|"SILENT_IGNORE"),"source_refs":r.8})).collect())
}

fn preview_export() -> Value {
    let rows = [
        (
            "PE-01",
            "React frame evaluation",
            "player-requested frame evaluation",
            "batch renderFrames evaluation",
            "SHARED_WITH_DIFFERENT_SCHEDULING",
            "Preview requests current targets and may coalesce work; export evaluates and retains the complete ordered frame set.",
            "Certify value equivalence separately from scheduling/completeness.",
            vec!["S-EVID-REACT-LOWER", "S-EVID-PLAYER-FALLBACK", "S-EVID-NODE-EXPORT"],
        ),
        (
            "PE-02",
            "CPU renderer core",
            "WASM CPU boundary",
            "native CPU boundary",
            "CONDITIONAL_PARITY",
            "Both consume Scene, but WASM and native use different host, font, filesystem, and media prepass environments.",
            "Require fixture parity with identical fonts and materialized media.",
            vec!["S-EVID-WASM-CPU", "S-EVID-CLI-RENDER"],
        ),
        (
            "PE-03",
            "GPU renderer core",
            "WASM Vello boundary",
            "native GPU boundary",
            "CONDITIONAL_PARITY",
            "The browser Vello engine is asynchronous WebGPU while native export selects and drives a native renderer path.",
            "Backend name alone is insufficient; compare exact-capability pixels.",
            vec!["S-EVID-WASM-GPU", "S-EVID-CLI-RENDER"],
        ),
        (
            "PE-04",
            "video decode",
            "browser media element/cache",
            "native media prepass",
            "DIFFERENT_EXECUTION",
            "Preview seeks HTML media and extracts data URIs or overlays; native render fetches to files and decodes before rendering.",
            "Video parity requires source-time, CORS, decode, and overlay exclusions.",
            vec!["S-EVID-VIDEO-PREVIEW", "S-EVID-CLI-MATERIALIZE"],
        ),
        (
            "PE-05",
            "audio scheduling",
            "AudioContext transport",
            "native audio/encoder path",
            "DIFFERENT_EXECUTION",
            "Preview anchors composition time to AudioContext and schedules ahead; export materializes audio for the encoder timeline.",
            "Audio certification must compare clock mapping and encoded mix, not preview audibility.",
            vec!["S-EVID-AUDIO-CLOCK", "S-EVID-CLI-MATERIALIZE"],
        ),
        (
            "PE-06",
            "Canvas2D",
            "approximate preview fallback",
            "not equivalent certification path",
            "KNOWN_APPROXIMATION",
            "Canvas2D implements only a subset and may omit or simplify nodes/effects.",
            "Any Canvas-selected run is excluded from renderer equivalence certification.",
            vec!["S-EVID-CANVAS-APPROX", "S-EVID-PLAYER-FALLBACK"],
        ),
        (
            "PE-07",
            "frame scheduling",
            "RAF may skip requested frames",
            "ordered complete export frame sequence",
            "DIFFERENT_EXECUTION",
            "The Player can skip intermediate targets while catching up; export must emit every requested frame in order.",
            "Temporal certification requires the export sequence, while preview is responsiveness evidence only.",
            vec!["S-EVID-PLAYER-FALLBACK", "S-EVID-REACT-LOWER"],
        ),
    ];
    Value::Array(rows.into_iter().map(|r|json!({"comparison_id":r.0,"feature":r.1,"preview_path":r.2,"export_path":r.3,"parity_class":r.4,"shared_authoring_evaluation":matches!(r.0,"PE-01"|"PE-02"|"PE-03"),"known_difference":r.5,"certification_impact":r.6,"source_refs":r.7})).collect())
}

fn creativity() -> Value {
    json!({
        "overall_verdict":"MULTI_LAYER_PROGRAMMABILITY_WITH_FINITE_RENDERER_VOCABULARY",
        "scoring_policy":"No numeric creativity score is assigned; every capability uses an evidence-backed categorical state that distinguishes native, host-language, registry, lower-level, finite-catalog, partial, and unknown support.",
        "surface_assessments":[
            creative_row("AS-CINEMA", [
                ("general_primitive_access", "REQUIRES_LOWER_LEVEL_SCENE_ACCESS"),
                ("procedural_logic", "SUPPORTED_THROUGH_CUSTOM_REGISTRY"),
                ("custom_geometry", "REQUIRES_LOWER_LEVEL_SCENE_ACCESS"),
                ("custom_animation", "SUPPORTED_THROUGH_CUSTOM_REGISTRY"),
                ("custom_component_extension", "SUPPORTED_THROUGH_CUSTOM_REGISTRY"),
                ("registry_dependence", "SUPPORTED_THROUGH_CUSTOM_REGISTRY"),
                ("named_pattern_dependence", "FINITE_CATALOG_LIMIT"),
                ("can_descend_to_primitives", "SUPPORTED_THROUGH_CUSTOM_REGISTRY"),
                ("inspectability", "PARTIALLY_SUPPORTED"),
                ("post_generation_editability", "PARTIALLY_SUPPORTED"),
                ("source_mapping", "PARTIALLY_SUPPORTED_BEFORE_LOWERING"),
                ("novel_scene_expressibility", "SUPPORTED_THROUGH_CUSTOM_REGISTRY"),
            ], "MEDIUM", "Custom registry code can emit React and reach Scene primitives, while built-in named patterns remain finite.", vec!["S-CINEMA-TYPES","S-CINEMA-COMPILER","S-CINEMA-RESOLVE","S-COMPONENTS"]),
            creative_row("AS-REACT", [
                ("general_primitive_access", "SUPPORTED"),
                ("procedural_logic", "SUPPORTED_THROUGH_HOST_LANGUAGE"),
                ("custom_geometry", "FINITE_CATALOG_LIMIT"),
                ("custom_animation", "SUPPORTED_THROUGH_HOST_LANGUAGE"),
                ("custom_component_extension", "SUPPORTED_THROUGH_HOST_LANGUAGE"),
                ("registry_dependence", "NOT_NATIVE"),
                ("named_pattern_dependence", "NOT_NATIVE"),
                ("can_descend_to_primitives", "SUPPORTED"),
                ("inspectability", "SUPPORTED"),
                ("post_generation_editability", "SUPPORTED_THROUGH_HOST_LANGUAGE"),
                ("source_mapping", "PARTIALLY_SUPPORTED"),
                ("novel_scene_expressibility", "SUPPORTED_THROUGH_HOST_LANGUAGE"),
            ], "LOW", "Frame hooks, interpolation, spring, sequencing, transitions, loops, and primitive nodes are directly available to host-language code.", vec!["S-MANDATORY-PACKAGES-REACT-SRC-INDEX-TS","S-MANDATORY-PACKAGES-REACT-SRC-COMPONENTS-TS","S-MANDATORY-PACKAGES-REACT-SRC-INTERPOLATE-TS","S-MANDATORY-PACKAGES-REACT-SRC-SPRING-TS","S-MANDATORY-PACKAGES-REACT-SRC-TRANSITIONS-TS","S-REACT-LOWER"]),
            creative_row("AS-JSON", [
                ("general_primitive_access", "SUPPORTED"),
                ("procedural_logic", "NOT_NATIVE"),
                ("custom_geometry", "FINITE_CATALOG_LIMIT"),
                ("custom_animation", "SUPPORTED"),
                ("custom_component_extension", "NOT_NATIVE"),
                ("registry_dependence", "NOT_NATIVE"),
                ("named_pattern_dependence", "NOT_NATIVE"),
                ("can_descend_to_primitives", "SUPPORTED"),
                ("inspectability", "SUPPORTED"),
                ("post_generation_editability", "SUPPORTED"),
                ("source_mapping", "PARTIALLY_SUPPORTED"),
                ("novel_scene_expressibility", "PARTIALLY_SUPPORTED"),
            ], "MEDIUM", "Direct JSON composes the finite Scene schema; it cannot define a new component implementation at this layer.", vec!["S-SCENE","S-CLI","S-WASM"]),
            creative_row("AS-RUST", [
                ("general_primitive_access", "SUPPORTED"),
                ("procedural_logic", "SUPPORTED_THROUGH_HOST_LANGUAGE"),
                ("custom_geometry", "FINITE_CATALOG_LIMIT"),
                ("custom_animation", "SUPPORTED_THROUGH_HOST_LANGUAGE"),
                ("custom_component_extension", "SUPPORTED_THROUGH_HOST_LANGUAGE"),
                ("registry_dependence", "NOT_NATIVE"),
                ("named_pattern_dependence", "NOT_NATIVE"),
                ("can_descend_to_primitives", "SUPPORTED"),
                ("inspectability", "SUPPORTED"),
                ("post_generation_editability", "SUPPORTED_THROUGH_HOST_LANGUAGE"),
                ("source_mapping", "PARTIALLY_SUPPORTED"),
                ("novel_scene_expressibility", "SUPPORTED_THROUGH_HOST_LANGUAGE"),
            ], "LOW", "Typed Rust constructs Scene and Timeline values directly without depending on the Cinema component registry.", vec!["S-SCENE","S-ANIMATION","S-CLI"]),
            creative_row("AS-COMPONENTS", [
                ("general_primitive_access", "REQUIRES_LOWER_LEVEL_SCENE_ACCESS"),
                ("procedural_logic", "SUPPORTED_THROUGH_CUSTOM_REGISTRY"),
                ("custom_geometry", "REQUIRES_LOWER_LEVEL_SCENE_ACCESS"),
                ("custom_animation", "SUPPORTED_THROUGH_CUSTOM_REGISTRY"),
                ("custom_component_extension", "SUPPORTED_THROUGH_CUSTOM_REGISTRY"),
                ("registry_dependence", "SUPPORTED_THROUGH_CUSTOM_REGISTRY"),
                ("named_pattern_dependence", "FINITE_CATALOG_LIMIT"),
                ("can_descend_to_primitives", "SUPPORTED_THROUGH_CUSTOM_REGISTRY"),
                ("inspectability", "PARTIALLY_SUPPORTED"),
                ("post_generation_editability", "PARTIALLY_SUPPORTED"),
                ("source_mapping", "PARTIALLY_SUPPORTED_BEFORE_LOWERING"),
                ("novel_scene_expressibility", "FINITE_CATALOG_LIMIT"),
            ], "MEDIUM", "Catalog identity is present before expansion, but complete component-to-Scene-to-pixel source mapping is not preserved.", vec!["S-COMPONENTS","S-MANDATORY-PACKAGES-COMPONENTS-SRC-INDEX-TS","S-CINEMA-COMPILER","S-REACT-LOWER"])
        ]
    })
}

fn creative_row<const N: usize>(
    surface_id: &str,
    capabilities: [(&str, &str); N],
    black_box_risk: &str,
    escape_hatch_evidence: &str,
    source_refs: Vec<&str>,
) -> Value {
    let mut row = serde_json::Map::new();
    row.insert("surface_id".into(), json!(surface_id));
    for (name, status) in capabilities {
        row.insert(name.into(), json!(status));
    }
    row.insert("black_box_risk".into(), json!(black_box_risk));
    row.insert("escape_hatch_evidence".into(), json!(escape_hatch_evidence));
    row.insert("source_refs".into(), json!(source_refs));
    Value::Object(row)
}

fn novel_scenes() -> Value {
    let laptop = [
        "part hierarchy",
        "segmentation",
        "exploded-view planning",
        "collision avoidance",
        "mechanical geometry",
        "materials",
        "emissive lighting",
        "camera",
        "particles",
        "timing",
        "sound",
        "semantic grouping",
        "inspectability",
        "editability",
        "asset truthfulness",
    ];
    let generic = |id: &str, name: &str, limits: &str| json!({"litmus_id":id,"scene":name,"verdict":"PARTIALLY_EXPRESSIBLE","required_primitives":["hierarchy","geometry","transforms","camera","timing","effects","media"],"surface_comparison":[{"surface_id":"AS-CINEMA","result":"guided composition; novel mechanics require registry code"},{"surface_id":"AS-REACT","result":"procedural composition over finite Scene primitives"},{"surface_id":"AS-JSON","result":"explicit renderer graph without high-level planning semantics"},{"surface_id":"AS-RUST","result":"typed procedural graph and timeline construction"},{"surface_id":"AS-COMPONENTS","result":"finite catalog unless extended with code"}],"capability_decomposition":[{"dimension":"overall primitive sufficiency","status":"PARTIAL_OR_NOT_ESTABLISHED","required_primitive":"inspectable scene-specific primitive composition","evidence_scope":"The cited Scene and React surfaces establish finite composition primitives, not a general solution for every requested visual or physical behavior.","source_refs":["S-SCENE","S-REACT-LOWER"]}],"limitations":limits,"inspectability":"Scene values are inspectable; high-level planning intent is not retained","editability":"value-level editing remains; semantic repair is weakened","asset_truthfulness":"external assets must be declared and cannot be inferred as physically accurate","source_refs":vec!["S-SCENE","S-REACT-LOWER","S-CINEMA-COMPILER","S-COMPONENTS"]});
    let mut laptop_scene=generic("LITMUS-LAPTOP","exploded laptop layers","general mechanical constraints, collision solving, physically based materials, and general shaders are not established");
    laptop_scene["capability_decomposition"] = Value::Array(laptop.into_iter().map(|dimension| {
        let (status, source_refs, evidence_scope) = match dimension {
            "part hierarchy" => ("SUPPORTED_OR_COMPOSABLE", vec!["S-SCENE", "S-REACT-LOWER"], "A presegmented model or manually supplied hierarchy can be composed."),
            "segmentation" => ("PARTIAL_OR_NOT_ESTABLISHED", vec!["S-SCENE", "S-REACT-LOWER"], "Manual or presegmented hierarchy is supported; automatic semantic or mechanical segmentation of a monolithic asset is not established."),
            "camera" | "timing" => ("SUPPORTED_OR_COMPOSABLE", vec!["S-SCENE", "S-REACT-LOWER"], "The cited authoring and Scene surfaces expose composable primitives for this dimension."),
            "sound" => ("SUPPORTED_OR_COMPOSABLE", vec!["S-AUDIO", "S-PLAYER", "S-REACT-LOWER"], "Audio authoring lowers to runtime scheduling with distinct clock ownership."),
            _ => ("PARTIAL_OR_NOT_ESTABLISHED", vec!["S-SCENE", "S-REACT-LOWER"], "The available finite primitives do not establish a general solution for this dimension."),
        };
        json!({"dimension":dimension,"status":status,"required_primitive":format!("inspectable {dimension} representation"),"evidence_scope":evidence_scope,"source_refs":source_refs})
    }).collect());
    let mut city_scene = generic(
        "LITMUS-CITY",
        "glass city revenue chart",
        "physically plausible transmissive glass and general lighting are not established",
    );
    city_scene["capability_decomposition"] = json!([
        {"dimension":"data-driven tower hierarchy","status":"SUPPORTED_OR_COMPOSABLE","required_primitive":"repeatable groups, shapes, and transforms","evidence_scope":"Host-language React can procedurally emit finite Scene nodes from data.","source_refs":["S-EVID-REACT-HOST","S-EVID-SCENE-NODES"]},
        {"dimension":"revenue-to-geometry mapping","status":"SUPPORTED_OR_COMPOSABLE","required_primitive":"numeric mapping into size and placement","evidence_scope":"Per-frame host-language evaluation can compute renderer-facing numeric properties.","source_refs":["S-EVID-REACT-LOWER"]},
        {"dimension":"transmissive glass material","status":"PARTIAL_OR_NOT_ESTABLISHED","required_primitive":"refractive/transmissive material with thickness","evidence_scope":"The finite NodeKind evidence does not establish a general physically based glass material.","source_refs":["S-EVID-SCENE-NODES"]},
        {"dimension":"city-scale lighting and reflections","status":"PARTIAL_OR_NOT_ESTABLISHED","required_primitive":"general lights, reflection environment, and shadows","evidence_scope":"Camera and finite effects do not prove general scene lighting or reflection probes.","source_refs":["S-EVID-SCENE-NODES"]},
        {"dimension":"semantic chart inspectability","status":"PARTIAL_OR_NOT_ESTABLISHED","required_primitive":"retained data-series and metric identity","evidence_scope":"Scene values remain inspectable, but chart semantics and source provenance are not retained after lowering.","source_refs":["S-EVID-REACT-LOWER","S-EVID-SCENE-DOCUMENT"]}
    ]);
    let mut spacecraft_scene = generic(
        "LITMUS-SPACECRAFT",
        "chrome liquid title spacecraft",
        "liquid simulation, reflective materials, and environment lighting are not established",
    );
    spacecraft_scene["capability_decomposition"] = json!([
        {"dimension":"spacecraft part hierarchy","status":"SUPPORTED_OR_COMPOSABLE","required_primitive":"nested geometry and transforms","evidence_scope":"Manually supplied or procedurally generated finite geometry can be grouped and transformed.","source_refs":["S-EVID-REACT-HOST","S-EVID-SCENE-NODES"]},
        {"dimension":"title-to-hull deformation","status":"PARTIAL_OR_NOT_ESTABLISHED","required_primitive":"inspectable text/mesh deformation mapping","evidence_scope":"Finite path/text primitives do not establish automatic semantic deformation into a spacecraft hull.","source_refs":["S-EVID-SCENE-NODES"]},
        {"dimension":"liquid simulation","status":"PARTIAL_OR_NOT_ESTABLISHED","required_primitive":"time-evolving fluid surface simulation","evidence_scope":"Host-language frame logic can author values, but no general fluid solver is established.","source_refs":["S-EVID-REACT-LOWER","S-EVID-SCENE-NODES"]},
        {"dimension":"chrome reflections","status":"PARTIAL_OR_NOT_ESTABLISHED","required_primitive":"reflective material and environment lighting","evidence_scope":"The cited renderer-facing vocabulary does not prove physically based chrome reflection.","source_refs":["S-EVID-SCENE-NODES"]},
        {"dimension":"camera and authored timing","status":"SUPPORTED_OR_COMPOSABLE","required_primitive":"camera fields, transforms, and per-frame evaluation","evidence_scope":"Explicit camera/transform values and host-language frame evaluation are available.","source_refs":["S-EVID-REACT-LOWER","S-EVID-SCENE-NODES"]},
        {"dimension":"source editability","status":"PARTIAL_OR_NOT_ESTABLISHED","required_primitive":"retained semantic source map for title, hull, and material intent","evidence_scope":"Final Scene remains value-editable but does not preserve source-level semantic provenance.","source_refs":["S-EVID-SCENE-DOCUMENT","S-EVID-REACT-LOWER"]}
    ]);
    Value::Array(vec![laptop_scene, city_scene, spacecraft_scene])
}

fn requirements() -> Value {
    json!([
        requirement("CK-R002-REQ-001", "Preserve stable source identity and source-map chains across lowering stages.", "Early identity loss weakens inspection and repair.", vec!["C-003","C-004","C-011"], vec!["S-CINEMA-TYPES","S-CINEMA-RESOLVE","S-CINEMA-COMPILER","S-SCENE"], vec!["E-MLIR"], vec!["P06","P07","P08","P09","P10","P14","P23","P25"], "Enables precise edits without reconstructing flattened authoring intent.", "Lets agents and reviewers trace rendered results to stable authored entities.", "Adds metadata and lookup cost that R0.03 and R0.07 must measure.", "Preserves semantic targets for open-ended generation and repair.", vec!["R0.03","R0.05","R0.07","R0.08"]),
        requirement("CK-R002-REQ-002", "Represent time domains and conversions explicitly.", "Fragmented clocks, rounding, and sampling obscure determinism.", vec!["C-007","C-010","C-011"], vec!["S-CINEMA-TIME","S-ANIMATION","S-PLAYER","S-VIDEO","S-AUDIO","S-CLI"], vec!["E-GSTREAMER"], vec!["P01","P02","P03","P07","P08","P14","P18","P19"], "Prevents timing drift across authoring, preview, media, and export.", "Makes rounding, rate ownership, and clock conversion auditable.", "Allows conversion and synchronization overhead to be measured explicitly.", "Gives procedural animation a deterministic temporal contract.", vec!["R0.03","R0.06","R0.07"]),
        requirement("CK-R002-REQ-003", "Separate semantic authoring IR from renderer IR through explicit lowering contracts.", "High-level intent is consumed before rendering.", vec!["C-003","C-004","C-005","C-011"], vec!["S-CINEMA-TYPES","S-CINEMA-COMPILER","S-REACT-LOWER","S-SCENE"], vec!["E-MLIR"], vec!["P05","P06","P07","P08","P09","P10","P14","P23","P25"], "Keeps authoring semantics available while renderer data stays constrained.", "Makes each semantic-loss boundary explicit and reviewable.", "Permits renderer IR optimization without silently changing authoring meaning.", "Supports novel high-level constructs without forcing them into a template catalog.", vec!["R0.03","R0.04","R0.05","R0.08"]),
        requirement("CK-R002-REQ-004", "Make capability fallback typed, diagnosed, and quality-classified.", "Automatic fallback can alter visible semantics.", vec!["C-007","C-008"], vec!["S-PLAYER","S-VIDEO","S-AUDIO","S-WASM","S-WASM-VELLO","S-CANVAS","S-CLI"], vec!["E-GSTREAMER"], vec!["P05","P08","P10","P14","P20","P21","P23","P24"], "Prevents silent quality loss when a backend or media capability is unavailable.", "Makes every demotion visible to users, agents, and certification logic.", "Supports capability-aware planning instead of repeated failing work.", "Lets authors deliberately choose approximations without mistaking them for equivalence.", vec!["R0.03","R0.04","R0.06","R0.07"]),
        requirement("CK-R002-REQ-005", "Support bounded streaming frame generation.", "Whole-video Scene materialization scales with duration and graph size.", vec!["C-006","C-009"], vec!["S-REACT-LOWER","S-NODE-EXPORT","S-LAYOUT","S-IMAGE","S-VIDEO","S-CLI"], vec!["E-GSTREAMER"], vec!["P08","P14","P18","P19","P20","P26"], "Avoids duration-driven exhaustion that can prevent otherwise valid renders.", "Makes buffering and materialization limits explicit failure contracts.", "Bounds memory and I/O, with thresholds reserved for R0.07 measurement.", "Allows long procedural works without requiring whole-program frame materialization.", vec!["R0.03","R0.07"]),
        requirement("CK-R002-REQ-006", "Version serialized boundaries with compatibility fixtures and negotiation.", "Current compatibility guarantees are incomplete.", vec!["C-005","C-011"], vec!["S-SCENE","S-CLI","S-WASM","S-WASM-VELLO"], vec!["E-MLIR"], vec!["P07","P08","P09","P10","P14","P18","P19","P23","P24"], "Prevents schema evolution from corrupting or rejecting valid creative documents unpredictably.", "Provides explicit compatibility evidence for stored and exchanged artifacts.", "Makes migration cost measurable and avoids accidental full recompilation paths.", "Protects editable creative programs across tool and runtime upgrades.", vec!["R0.03","R0.06","R0.08"]),
        requirement("CK-R002-REQ-007", "Preserve deterministic random, media, and global-state ownership contracts.", "Module-global and external runtime state complicate reentrancy.", vec!["C-002","C-010","C-012"], vec!["S-REACT-FRAME","S-REACT-STATE","S-REACT-WARM","S-PLAYER","S-VIDEO","S-AUDIO","S-REACT-LOWER"], vec!["E-REACT","E-GSTREAMER"], vec!["P01","P02","P03","P07","P08","P14","P18","P19","P20","P21"], "Produces repeatable frames under concurrency, seeking, and retries.", "Makes nondeterministic state ownership observable and testable.", "Enables safe parallelism only where isolation costs and benefits are known.", "Keeps procedural randomness and media behavior reproducible for agent iteration.", vec!["R0.03","R0.06","R0.07"]),
        requirement("CK-R002-REQ-008", "Keep open-ended host-language escape hatches while retaining inspectable primitives.", "Finite catalogs alone cannot guarantee novel-scene expressibility.", vec!["C-001","C-003","C-005"], vec!["S-MANDATORY-PACKAGES-REACT-SRC-INDEX-TS","S-MANDATORY-PACKAGES-REACT-SRC-COMPONENTS-TS","S-CINEMA-COMPILER","S-COMPONENTS","S-SCENE"], vec!["E-REACT","E-MLIR"], vec!["P01","P02","P03","P05","P06","P07","P25","P26","P28"], "Combines reusable components with precise low-level control.", "Keeps generated structures inspectable instead of hiding behavior behind opaque presets.", "Allows specialization while retaining analyzable primitive output and later measurement.", "Maintains the project goal of general creative programming rather than template selection.", vec!["R0.04","R0.05","R0.06","R0.08"])
    ])
}

#[allow(clippy::too_many_arguments)]
fn requirement(
    requirement_id: &str,
    abstract_requirement: &str,
    problem_addressed: &str,
    observations: Vec<&str>,
    onda_sources: Vec<&str>,
    primary_sources: Vec<&str>,
    programs: Vec<&str>,
    quality: &str,
    trust: &str,
    performance: &str,
    creativity: &str,
    follow_up: Vec<&str>,
) -> Value {
    json!({"requirement_id":requirement_id,"abstract_requirement":abstract_requirement,"problem_addressed":problem_addressed,"onda_observation_refs":observations,"onda_source_refs":onda_sources,"independent_primary_source_refs":primary_sources,"affected_cinekernel_programs":programs,"quality_impact":quality,"trust_impact":trust,"performance_impact":performance,"creative_programming_impact":creativity,"required_follow_up_research":follow_up,"prohibited_reuse_note":"Abstract requirement only; no ONDA code, schema, API, naming, or implementation detail may be reused.","status":"CANDIDATE_ONLY"})
}

fn contradictions() -> Value {
    json!([{"contradiction_id":"CON-001","statement":"Fresh React roots isolate host trees, but module-global active frame and depth-of-field state leave concurrent or nested reentrancy unresolved.","source_refs":["S-REACT-LOWER"]},{"contradiction_id":"CON-002","statement":"Renderer sharing does not imply end-to-end preview/export parity because media scheduling and fallbacks differ.","source_refs":["S-PLAYER","S-VIDEO","S-AUDIO","S-CLI"]},{"contradiction_id":"CON-003","statement":"A universal Scene vocabulary is still finite and Canvas preview explicitly approximates only a subset.","source_refs":["S-SCENE","S-CANVAS"]}])
}

fn deferred() -> Value {
    json!([{"topic_id":"DEF-001","phase":"R0.03","topic":"Native GPU, CPU, WASM, and encoding architecture"},{"topic_id":"DEF-002","phase":"R0.04","topic":"Typography, layout, effects, color, and 3D architecture"},{"topic_id":"DEF-003","phase":"R0.05","topic":"Agent component catalog and cinematic composition model"},{"topic_id":"DEF-004","phase":"R0.06","topic":"CLI, installation, preview, embedding, and developer experience"},{"topic_id":"DEF-005","phase":"R0.07","topic":"Independent benchmark and failure analysis"},{"topic_id":"DEF-006","phase":"R0.08","topic":"Adoption, rejection, clean-room, and roadmap-delta matrix"}])
}

fn open_questions() -> Value {
    json!([
        {"id":"Q-001","question":"What scene-size and duration thresholds make full frame materialization unacceptable on target machines?","defer_to":["R0.03","R0.07"],"source_refs":["S-NODE-EXPORT","S-REACT-LOWER"]},
        {"id":"Q-002","question":"Which renderer capabilities are intentionally stable across CPU, Vello, and browser hosts?","defer_to":["R0.03"],"source_refs":["S-WASM","S-WASM-VELLO","S-CLI"]},
        {"id":"Q-003","question":"What serialization evolution policy is promised beyond current version handling?","defer_to":["R0.03","R0.08"],"source_refs":["S-SCENE","S-CLI","S-WASM"]},
        {"id":"Q-004","question":"How should media clocks, frame rates, variable frame rate, and audio resampling compose?","defer_to":["R0.03","R0.06","R0.07"],"source_refs":["S-AUDIO","S-VIDEO","S-CLI"]},
        {"id":"Q-005","question":"What general material, shader, constraint, and simulation model is required for the target creative ceiling?","defer_to":["R0.04"],"source_refs":["S-SCENE","S-COMPONENTS"]},
        {"id":"Q-006","question":"Which authoring semantics must remain editable after lowering and round-trip serialization?","defer_to":["R0.05","R0.08"],"source_refs":["S-CINEMA-TYPES","S-CINEMA-COMPILER"]}
    ])
}
